// =============================================================================
// design.sv  —  AXI-Lite-over-UCIe (AoU) to AXI-Lite memory : full DUT RTL.
//
// AUTO-GENERATED by 'make -C uvm eda' — do not edit by hand.  Regenerate after
// any rtl/ change.  Concatenation of rtl/*.sv (package first, then leaf modules,
// then the top), for the EDA Playground DESIGN pane; pair with testbench.sv.
// =============================================================================

// ==================== rtl/aou_pkg.sv ====================
// -----------------------------------------------------------------------------
// aou_pkg : AXI-over-UCIe (AoU) Basic-Profile message + flit definitions.
//
// Source: "AXI over UCIe Protocol Specification v0.8" (OCA / Tenstorrent),
//   Chapter 4 (Packing) and Chapter 5 (Message Structures).
//
// Scope of THIS package (see docs/PLAN.md):
//   * Basic Profile messages: WriteReq, ReadReq, WriteData(256b),
//     ReadData(256b), WriteResp.  (WriteDataFull / 512b / 1024b not built.)
//   * Resource Plane RP0 only; §6 per-message-type credit flow control (see the
//     credit helpers below and the bridges); no activation FSM (§8).
//   * AXI4-Lite front door, 32-bit data / 32-bit address, single beat
//     (AWLEN=ARLEN=0, DLENGTH=00 -> 256b data message).
//
// Bit-ordering convention (documented, shared by packer + unpacker):
//   * A message is packed MSB-first in spec table order (Tables 2,3,4,10,13):
//     the first table field lands in the most-significant bits.
//   * Each message is left-justified in an MSG_MAX_BITS (=320b) vector, so
//     message granule 0 is always the MSB slice [319:280].
//   * The 240B PLP payload is NUM_GRAN granules of GRAN_BITS bits each, granule
//     0 = most-significant.  A message of N granules starting at granule g
//     occupies payload[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: N*GRAN_BITS].
//   Field order, widths and granule counts match the §5.8 message layouts
//   exactly (byte 0 first, MSB-first fields), and the §4.3 protocol header uses
//   the exact Figure-5 byte map (FDId/MsgStart/MsgCredit/Rsvd scattered across
//   the 10 header bytes, LSB-first).  flit_get_byte() exposes the byte-exact
//   PLP for conformance checking.
// -----------------------------------------------------------------------------
`ifndef AOU_PKG_SV
`define AOU_PKG_SV

// This is a protocol-definition package: it deliberately declares the full
// Basic-Profile field set (including reserved fields and the 512b/1024b DLENGTH
// encodings this build does not yet use), and its field getters each read only
// the slice of a message they need.  Both are intentional, so waive the
// "unused" lints that would otherwise fire on the package in isolation.
// verilator lint_off UNUSEDPARAM
// verilator lint_off UNUSEDSIGNAL
package aou_pkg;

  // --- Flit / PLP geometry (spec §4.2) --------------------------------------
  localparam int GRAN_BITS         = 40;                 // 5 bytes per granule
  localparam int NUM_GRAN          = 48;                 // 240B payload / 5B
  localparam int PLP_PAYLOAD_BITS  = GRAN_BITS * NUM_GRAN; // 1920
  localparam int PLP_HDR_BITS      = 80;                 // 10B protocol header
  localparam int PLP_BITS          = PLP_HDR_BITS + PLP_PAYLOAD_BITS; // 2000 (250B)

  localparam int FDID_W  = 2;                           // Flit Destination ID
  localparam int CREDIT_W = 16;                          // MsgCredit field
  localparam int HDR_RSVD_W = PLP_HDR_BITS - FDID_W - NUM_GRAN - CREDIT_W; // 14

  typedef logic [PLP_BITS-1:0]         flit_t;           // 250B PLP == link word
  typedef logic [PLP_PAYLOAD_BITS-1:0] payload_t;        // 240B / 48 granules
  typedef logic [NUM_GRAN-1:0]         msgstart_t;       // MsgStart bitmap

  // --- MSGTYPE encoding (spec Table 1) --------------------------------------
  localparam int MSGTYPE_W = 4;
  typedef enum logic [MSGTYPE_W-1:0] {
    MT_MISC          = 4'b0000,
    MT_WRITEREQ      = 4'b0001,
    MT_READREQ       = 4'b0010,
    MT_WRITEDATA     = 4'b0011,
    MT_READDATA      = 4'b0100,
    MT_WRITERESP     = 4'b0101,
    MT_WRITEDATAFULL = 4'b0110
  } msgtype_e;

  // --- AoU-specific + AXI-equivalent field widths (Basic Profile) -----------
  localparam int RP_W      = 2;    // resource plane
  localparam int DLENGTH_W = 2;    // data-message width selector
  localparam int FLEX_W    = 16;   // USER[15:0] in Basic Profile
  localparam int AOU_ID_W  = 10;   // AWID/ARID/BID/RID
  localparam int AOU_SIZE_W  = 3;
  localparam int AOU_PROT_W  = 3;
  localparam int AOU_LEN_W   = 8;
  localparam int AOU_CACHE_W = 4;
  localparam int AOU_QOS_W   = 4;
  localparam int AOU_ADDR_W  = 64;
  localparam int AOU_DATA_W  = 256;  // WriteData/ReadData(256b)
  localparam int AOU_STRB_W  = 32;
  localparam int AOU_RESP_W  = 2;    // RRESP/BRESP

  // DLENGTH encodings (spec §5.4).  This design uses 256b only.
  localparam logic [DLENGTH_W-1:0] DLEN_256  = 2'b00;
  localparam logic [DLENGTH_W-1:0] DLEN_512  = 2'b01;
  localparam logic [DLENGTH_W-1:0] DLEN_1024 = 2'b10;

  // --- Message bit-lengths and granule counts (spec §5.3-5.5) ---------------
  localparam int WRITEREQ_BITS  = 120; localparam int WRITEREQ_GRAN  = 3;
  localparam int READREQ_BITS   = 120; localparam int READREQ_GRAN   = 3;
  localparam int WRITEDATA_BITS = 320; localparam int WRITEDATA_GRAN = 8;
  localparam int READDATA_BITS  = 320; localparam int READDATA_GRAN  = 8;
  localparam int WRITERESP_BITS = 40;  localparam int WRITERESP_GRAN = 1;

  localparam int MSG_MAX_BITS = 320;   // largest built message (WriteData256)
  localparam int MSG_MAX_GRAN = 8;

  typedef logic [MSG_MAX_BITS-1:0] msg_t;   // left-justified message container

  // granule count for a decoded MSGTYPE (0 = unknown/unsupported)
  function automatic int msg_granules(input logic [MSGTYPE_W-1:0] mt);
    case (mt)
      MT_WRITEREQ  : msg_granules = WRITEREQ_GRAN;
      MT_READREQ   : msg_granules = READREQ_GRAN;
      MT_WRITEDATA : msg_granules = WRITEDATA_GRAN;
      MT_READDATA  : msg_granules = READDATA_GRAN;
      MT_WRITERESP : msg_granules = WRITERESP_GRAN;
      default      : msg_granules = 0;
    endcase
  endfunction

  // =========================================================================
  // Message builders.  Each returns an MSG_MAX_BITS vector with the message
  // left-justified (granule 0 in the MSBs) and low bits zero-padded.
  // AXI-Lite fields are widened into the AoU fields (addr/data zero-extended,
  // id placed in the low bits of the 10-bit AoU id field).
  // =========================================================================

  // WriteReq (Table 2): MSGTYPE,RP,RsvdZero(1),AWLOCK,FLEX,AWID,AWSIZE,AWPROT,
  //                     AWLEN,AWCACHE,AWQOS,AWADDR  => 120b
  function automatic msg_t mk_writereq(
      input logic [RP_W-1:0]        rp,
      input logic                   awlock,
      input logic [FLEX_W-1:0]      flex,
      input logic [AOU_ID_W-1:0]    awid,
      input logic [AOU_SIZE_W-1:0]  awsize,
      input logic [AOU_PROT_W-1:0]  awprot,
      input logic [AOU_LEN_W-1:0]   awlen,
      input logic [AOU_CACHE_W-1:0] awcache,
      input logic [AOU_QOS_W-1:0]   awqos,
      input logic [AOU_ADDR_W-1:0]  awaddr);
    logic [WRITEREQ_BITS-1:0] v;
    begin
      v = {MT_WRITEREQ, rp, 1'b0, awlock, flex, awid, awsize, awprot,
           awlen, awcache, awqos, awaddr};
      mk_writereq = {v, {(MSG_MAX_BITS-WRITEREQ_BITS){1'b0}}};
    end
  endfunction

  // ReadReq (Table 3): symmetric to WriteReq => 120b
  function automatic msg_t mk_readreq(
      input logic [RP_W-1:0]        rp,
      input logic                   arlock,
      input logic [FLEX_W-1:0]      flex,
      input logic [AOU_ID_W-1:0]    arid,
      input logic [AOU_SIZE_W-1:0]  arsize,
      input logic [AOU_PROT_W-1:0]  arprot,
      input logic [AOU_LEN_W-1:0]   arlen,
      input logic [AOU_CACHE_W-1:0] arcache,
      input logic [AOU_QOS_W-1:0]   arqos,
      input logic [AOU_ADDR_W-1:0]  araddr);
    logic [READREQ_BITS-1:0] v;
    begin
      v = {MT_READREQ, rp, 1'b0, arlock, flex, arid, arsize, arprot,
           arlen, arcache, arqos, araddr};
      mk_readreq = {v, {(MSG_MAX_BITS-READREQ_BITS){1'b0}}};
    end
  endfunction

  // WriteData 256b (Table 4): MSGTYPE,RP,DLENGTH,FLEX,WDATA(256),WSTRB(32),
  //                           RsvdZero(8) => 320b (exactly MSG_MAX_BITS)
  function automatic msg_t mk_writedata256(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_DATA_W-1:0] wdata,
      input logic [AOU_STRB_W-1:0] wstrb);
    mk_writedata256 = {MT_WRITEDATA, rp, DLEN_256, flex, wdata, wstrb, 8'b0};
  endfunction

  // ReadData 256b (Table 10): MSGTYPE,RP,DLENGTH,FLEX,RID,RRESP,RLAST,
  //   RsvdZero(3),RDATA(256),RsvdZero(24) => 320b
  function automatic msg_t mk_readdata256(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_ID_W-1:0]   rid,
      input logic [AOU_RESP_W-1:0] rresp,
      input logic                  rlast,
      input logic [AOU_DATA_W-1:0] rdata);
    mk_readdata256 = {MT_READDATA, rp, DLEN_256, flex, rid, rresp, rlast,
                      3'b0, rdata, 24'b0};
  endfunction

  // WriteResp (Table 13): MSGTYPE,RP,RsvdZero(2),FLEX,BID,BRESP,RsvdZero(4)
  //                       => 40b (1 granule) left-justified in 320b
  function automatic msg_t mk_writeresp(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_ID_W-1:0]   bid,
      input logic [AOU_RESP_W-1:0] bresp);
    logic [WRITERESP_BITS-1:0] v;
    begin
      v = {MT_WRITERESP, rp, 2'b0, flex, bid, bresp, 4'b0};
      mk_writeresp = {v, {(MSG_MAX_BITS-WRITERESP_BITS){1'b0}}};
    end
  endfunction

  // =========================================================================
  // Field extractors.  Input `m` is a left-justified MSG_MAX_BITS slice (the
  // unpacker builds it by taking N granules from the payload and zero-padding
  // the low bits).  MSGTYPE is always m[MSG_MAX_BITS-1 -: 4].
  // =========================================================================
  function automatic logic [MSGTYPE_W-1:0] get_msgtype(input msg_t m);
    get_msgtype = m[MSG_MAX_BITS-1 -: MSGTYPE_W];
  endfunction

  // WriteReq field getters
  function automatic logic [AOU_ADDR_W-1:0] wr_addr(input msg_t m);
    // AWADDR is the last (LSB) field of the 120b message
    wr_addr = m[(MSG_MAX_BITS-WRITEREQ_BITS) +: AOU_ADDR_W];
  endfunction
  function automatic logic [AOU_ID_W-1:0] wr_id(input msg_t m);
    // AWID sits after MSGTYPE(4),RP(2),RsvdZero(1),AWLOCK(1),FLEX(16) = 24 bits
    wr_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [FLEX_W-1:0] wr_flex(input msg_t m);
    wr_flex = m[MSG_MAX_BITS-1-8 -: FLEX_W];  // after 4+2+1+1 = 8 bits
  endfunction
  function automatic logic [AOU_SIZE_W-1:0] wr_size(input msg_t m);
    wr_size = m[MSG_MAX_BITS-1-34 -: AOU_SIZE_W];   // after 24 + AWID(10)
  endfunction
  function automatic logic [AOU_LEN_W-1:0] wr_len(input msg_t m);
    wr_len = m[MSG_MAX_BITS-1-40 -: AOU_LEN_W];     // after 34 + AWSIZE(3)+AWPROT(3)
  endfunction
  // AoU Table 2 WriteReq has no AWBURST field; the burst type rides in FLEX[1:0]
  // as a Basic-Profile extension (§5.2 FLEX "additional information / extensions").
  function automatic logic [1:0] wr_burst(input msg_t m);
    logic [FLEX_W-1:0] f;                 // temp: Icarus rejects func(...)[range]
    begin f = wr_flex(m); wr_burst = f[1:0]; end
  endfunction

  // ReadReq field getters (identical layout to WriteReq)
  function automatic logic [AOU_ADDR_W-1:0] rr_addr(input msg_t m);
    rr_addr = m[(MSG_MAX_BITS-READREQ_BITS) +: AOU_ADDR_W];
  endfunction
  function automatic logic [AOU_ID_W-1:0] rr_id(input msg_t m);
    rr_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [FLEX_W-1:0] rr_flex(input msg_t m);
    rr_flex = m[MSG_MAX_BITS-1-8 -: FLEX_W];
  endfunction
  function automatic logic [AOU_SIZE_W-1:0] rr_size(input msg_t m);
    rr_size = m[MSG_MAX_BITS-1-34 -: AOU_SIZE_W];
  endfunction
  function automatic logic [AOU_LEN_W-1:0] rr_len(input msg_t m);
    rr_len = m[MSG_MAX_BITS-1-40 -: AOU_LEN_W];
  endfunction
  function automatic logic [1:0] rr_burst(input msg_t m);
    logic [FLEX_W-1:0] f;
    begin f = rr_flex(m); rr_burst = f[1:0]; end
  endfunction

  // AXI burst types (AxBURST encoding).  Carried in FLEX[1:0] (see wr_burst).
  localparam logic [1:0] AXBURST_FIXED = 2'b00;
  localparam logic [1:0] AXBURST_INCR  = 2'b01;
  localparam logic [1:0] AXBURST_WRAP  = 2'b10;

  // Next-beat address for an AXI burst (FIXED/INCR/WRAP), per the AXI4 spec.
  //   addr = current beat address, base = burst start address,
  //   size = log2(bytes/beat), len = AxLEN (beats-1).
  // WRAP wraps at the aligned boundary of (len+1)*2^size bytes (len+1 in {2,4,
  // 8,16}); FIXED holds the address; INCR increments by 2^size.
  function automatic logic [AOU_ADDR_W-1:0] axi_burst_next(
      input logic [AOU_ADDR_W-1:0] addr,
      input logic [AOU_ADDR_W-1:0] base,
      input logic [1:0]            burst,
      input logic [AOU_SIZE_W-1:0] size,
      input logic [AOU_LEN_W-1:0]  len);
    logic [AOU_ADDR_W-1:0] nbytes, total, low, nxt;
    begin
      nbytes = (1 << size);
      unique case (burst)
        AXBURST_FIXED: axi_burst_next = addr;
        AXBURST_WRAP: begin
          total = ({{(AOU_ADDR_W-AOU_LEN_W){1'b0}}, len} + 1) << size;
          low   = base & ~(total - 1);
          nxt   = addr + nbytes;
          axi_burst_next = (nxt == (low + total)) ? low : nxt;
        end
        default: axi_burst_next = addr + nbytes;   // AXBURST_INCR
      endcase
    end
  endfunction

  // WriteData256 getters: after MSGTYPE(4),RP(2),DLENGTH(2),FLEX(16) = 24 bits
  function automatic logic [AOU_DATA_W-1:0] wd_data(input msg_t m);
    wd_data = m[MSG_MAX_BITS-1-24 -: AOU_DATA_W];
  endfunction
  function automatic logic [AOU_STRB_W-1:0] wd_strb(input msg_t m);
    wd_strb = m[MSG_MAX_BITS-1-24-AOU_DATA_W -: AOU_STRB_W];
  endfunction

  // ReadData256 getters: MSGTYPE(4),RP(2),DLENGTH(2),FLEX(16),RID(10),
  //   RRESP(2),RLAST(1),RsvdZero(3) then RDATA(256)
  function automatic logic [AOU_ID_W-1:0] rd_id(input msg_t m);
    rd_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [AOU_RESP_W-1:0] rd_resp(input msg_t m);
    rd_resp = m[MSG_MAX_BITS-1-34 -: AOU_RESP_W];  // after 24+10
  endfunction
  function automatic logic rd_last(input msg_t m);
    rd_last = m[MSG_MAX_BITS-1-36];                // after 24+10+2
  endfunction
  function automatic logic [AOU_DATA_W-1:0] rd_data(input msg_t m);
    rd_data = m[MSG_MAX_BITS-1-40 -: AOU_DATA_W];  // after 24+10+2+1+3 = 40
  endfunction

  // WriteResp getters: after MSGTYPE(4),RP(2),RsvdZero(2),FLEX(16) = 24 bits
  function automatic logic [AOU_ID_W-1:0] wrsp_id(input msg_t m);
    wrsp_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [AOU_RESP_W-1:0] wrsp_resp(input msg_t m);
    wrsp_resp = m[MSG_MAX_BITS-1-34 -: AOU_RESP_W];
  endfunction

  // =========================================================================
  // Flit assembly / disassembly (spec §4.2-4.3, byte-exact).
  //
  // The 250B PLP is a 10B protocol header (PH B0..B9) followed by the 240B
  // payload.  Per §4.3 (Figure 5) the header fields are NOT contiguous: FDId,
  // the 48-bit MsgStart bitmap, the 16-bit MsgCredit word, and 14 Rsvd bits are
  // scattered across the ten header bytes at fixed byte/bit positions.  Unlike
  // the §5.8 message fields (packed MSB-first), the header packs each field
  // LSB-first — MsgStart[0], MsgCredit[0], FDId[0] are the earliest bits.  We
  // model that exact layout so flit_get_byte() reproduces the spec's byte map.
  //
  // Let g be a header bit's transmission order (g=0 is PH B0's first bit); it
  // sits at flit[PLP_BITS-1-g].  The payload is flit[PLP_PAYLOAD_BITS-1:0].
  //   FDId[j]      : g = j              (PH B0 labels 0..1)
  //   MsgCredit[j] : g = 32 + j         (PH B4/B5)
  //   MsgStart[i]  : g = msgstart_g(i)  (scattered across B0..B3, B6..B9)
  //   Rsvd (=0)    : g in {2,3, 16..19, 48..51, 64..67}
  // =========================================================================

  // Transmission-order bit index of MsgStart[i] within the header (Figure 5:
  // MsgStart occupies PH B0[4:7],B1,B2[4:7],B3 then B6[4:7],B7,B8[4:7],B9).
  function automatic int msgstart_g(input int i);
    if      (i <= 11) msgstart_g = i + 4;    // B0[4:7], B1, B2[4:7]start
    else if (i <= 23) msgstart_g = i + 8;    // B2[4:7], B3
    else if (i <= 35) msgstart_g = i + 28;   // B6[4:7], B7
    else              msgstart_g = i + 32;   // B8[4:7], B9
  endfunction

  function automatic flit_t flit_assemble_cr(input logic [FDID_W-1:0]   fdid,
                                             input msgstart_t           msgstart,
                                             input logic [CREDIT_W-1:0] msgcredit,
                                             input payload_t            payload);
    flit_t f;
    begin
      f = '0;
      f[PLP_PAYLOAD_BITS-1:0] = payload;
      for (int j = 0; j < FDID_W;   j++) f[PLP_BITS-1 - j]            = fdid[j];
      for (int j = 0; j < CREDIT_W; j++) f[PLP_BITS-1 - (32 + j)]     = msgcredit[j];
      for (int i = 0; i < NUM_GRAN; i++) f[PLP_BITS-1 - msgstart_g(i)] = msgstart[i];
      flit_assemble_cr = f;                  // Rsvd bits left at 0
    end
  endfunction

  // MsgCredit=0 convenience wrapper (used where no credit is advertised).
  function automatic flit_t flit_assemble(input logic [FDID_W-1:0] fdid,
                                          input msgstart_t         msgstart,
                                          input payload_t          payload);
    flit_assemble = flit_assemble_cr(fdid, msgstart, {CREDIT_W{1'b0}}, payload);
  endfunction

  function automatic msgstart_t flit_msgstart(input flit_t f);
    msgstart_t m;
    begin
      m = '0;
      for (int i = 0; i < NUM_GRAN; i++) m[i] = f[PLP_BITS-1 - msgstart_g(i)];
      flit_msgstart = m;
    end
  endfunction

  function automatic logic [CREDIT_W-1:0] flit_credit(input flit_t f);
    logic [CREDIT_W-1:0] c;
    begin
      c = '0;
      for (int j = 0; j < CREDIT_W; j++) c[j] = f[PLP_BITS-1 - (32 + j)];
      flit_credit = c;
    end
  endfunction

  function automatic logic [FDID_W-1:0] flit_fdid(input flit_t f);
    logic [FDID_W-1:0] d;
    begin
      d = '0;
      for (int j = 0; j < FDID_W; j++) d[j] = f[PLP_BITS-1 - j];
      flit_fdid = d;
    end
  endfunction

  function automatic payload_t flit_payload(input flit_t f);
    flit_payload = f[PLP_PAYLOAD_BITS-1:0];
  endfunction

  // Byte-addressable §4.3/§5.8 view: PLP byte 0 = PH B0 (first on the wire),
  // bytes 10.. are payload granule bytes; byte idx's label-0 bit is its MSB.
  function automatic logic [7:0] flit_get_byte(input flit_t f, input int idx);
    flit_get_byte = f[PLP_BITS-1 - idx*8 -: 8];
  endfunction

  // Place a (left-justified) message of `gran` granules into a payload at
  // granule `g`.  Returns the payload bits to be OR-ed / assigned.
  function automatic payload_t payload_put(input payload_t base,
                                           input int       g,
                                           input int       gran,
                                           input msg_t     m);
    payload_t p;
    begin
      p = base;
      // granule g occupies payload[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: 40];
      // a `gran`-granule message spans gran*GRAN_BITS bits from that top.
      for (int b = 0; b < gran*GRAN_BITS; b++)
        p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS - b] = m[MSG_MAX_BITS-1 - b];
      payload_put = p;
    end
  endfunction

  // Extract the message that starts at granule `g` (length `gran`) from a
  // payload, returned left-justified in an MSG_MAX_BITS container.
  function automatic msg_t payload_get(input payload_t p,
                                       input int       g,
                                       input int       gran);
    msg_t m;
    begin
      m = '0;
      for (int b = 0; b < gran*GRAN_BITS; b++)
        m[MSG_MAX_BITS-1 - b] = p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS - b];
      payload_get = m;
    end
  endfunction

  // MSGTYPE of the message starting at granule g (top 4 bits of that granule).
  function automatic logic [MSGTYPE_W-1:0] payload_msgtype(input payload_t p,
                                                           input int g);
    payload_msgtype = p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: MSGTYPE_W];
  endfunction

  // =========================================================================
  // §6 Flow control — per-message-type, per-granule credits (Basic Profile,
  // resource plane RP0).  A credit guarantees the receiver has room for one
  // granule of the advertised message type (§6.1); all of a message's credits
  // are consumed by the transmitter at its start.  Credits are advertised in
  // the 16-bit MsgCredit header field, sub-divided per Table 16 and value-
  // encoded in coarse buckets per Table 17.
  // =========================================================================

  // Per-type credit sub-field widths (Table 16).
  localparam int WREQCRED_W  = 3;   // MsgCredit[2:0]
  localparam int RREQCRED_W  = 3;   // MsgCredit[5:3]
  localparam int WDATACRED_W = 3;   // MsgCredit[8:6]
  localparam int RDATACRED_W = 3;   // MsgCredit[11:9]
  localparam int WRESPCRED_W = 2;   // MsgCredit[13:12]  (RP is MsgCredit[15:14])

  localparam int CRED_MAX = 128;    // largest grant (Table 17 'b111)

  // Table 17: a *CRED bucket code -> number of granted credits.
  function automatic int unsigned cred_decode(input logic [2:0] code);
    case (code)
      3'b000: cred_decode = 0;
      3'b001: cred_decode = 1;
      3'b010: cred_decode = 4;
      3'b011: cred_decode = 8;
      3'b100: cred_decode = 16;
      3'b101: cred_decode = 32;
      3'b110: cred_decode = 64;
      3'b111: cred_decode = 128;
      default:cred_decode = 0;
    endcase
  endfunction

  // Smallest Table-17 bucket granting at least `n` credits (n<=128 saturates).
  // Used to return "at least the granules just freed"; the peer counter then
  // saturates at its ceiling, so a coarse over-grant is harmless (§6.4).
  function automatic logic [2:0] cred_encode_ge(input logic [7:0] n);
    if      (n == 0) cred_encode_ge = 3'b000;
    else if (n <= 1) cred_encode_ge = 3'b001;
    else if (n <= 4) cred_encode_ge = 3'b010;
    else if (n <= 8) cred_encode_ge = 3'b011;
    else if (n <= 16) cred_encode_ge = 3'b100;
    else if (n <= 32) cred_encode_ge = 3'b101;
    else if (n <= 64) cred_encode_ge = 3'b110;
    else              cred_encode_ge = 3'b111;
  endfunction

  // 2-bit variant for the WRESPCRED field (Table 16): only the first four
  // Table-17 encodings are legal for WriteResp (up to 8 credits).
  function automatic logic [1:0] cred_encode_ge2(input logic [7:0] n);
    if      (n == 0) cred_encode_ge2 = 2'b00;
    else if (n <= 1) cred_encode_ge2 = 2'b01;
    else if (n <= 4) cred_encode_ge2 = 2'b10;
    else             cred_encode_ge2 = 2'b11;
  endfunction

  // Assemble a MsgCredit word (Table 16): RP in [15:14], then the five
  // per-type bucket codes.  Inputs are already Table-17 bucket codes.
  function automatic logic [CREDIT_W-1:0] mk_msgcredit(
      input logic [RP_W-1:0]        rp,
      input logic [WREQCRED_W-1:0]  wreq,
      input logic [RREQCRED_W-1:0]  rreq,
      input logic [WDATACRED_W-1:0] wdata,
      input logic [RDATACRED_W-1:0] rdata,
      input logic [WRESPCRED_W-1:0] wresp);
    mk_msgcredit = {rp, wresp, rdata, wdata, rreq, wreq};
  endfunction

  // MsgCredit sub-field extractors (Table 16).
  function automatic logic [2:0]      mc_wreq (input logic [CREDIT_W-1:0] c); mc_wreq  = c[2:0];   endfunction
  function automatic logic [2:0]      mc_rreq (input logic [CREDIT_W-1:0] c); mc_rreq  = c[5:3];   endfunction
  function automatic logic [2:0]      mc_wdata(input logic [CREDIT_W-1:0] c); mc_wdata = c[8:6];   endfunction
  function automatic logic [2:0]      mc_rdata(input logic [CREDIT_W-1:0] c); mc_rdata = c[11:9];  endfunction
  function automatic logic [1:0]      mc_wresp(input logic [CREDIT_W-1:0] c); mc_wresp = c[13:12]; endfunction
  function automatic logic [RP_W-1:0] mc_rp   (input logic [CREDIT_W-1:0] c); mc_rp    = c[15:14]; endfunction

  // =========================================================================
  // Miscellaneous messages (§5.6) — MSGTYPE = MT_MISC ('b0000), then a 3-bit
  // MISCOP (Table 15).  Used for §6.4.2 credit grants (CrdtGrant) and §8
  // interface state management (Activation).  Built MSB-first, left-justified
  // in an MSG_MAX_BITS container like the §5.8 data messages.
  // =========================================================================
  localparam int MISCOP_W       = 3;
  localparam int ACTIVATIONOP_W = 4;

  // MISCOP encoding (Table 15).
  localparam logic [MISCOP_W-1:0] MISCOP_ACTIVATION = 3'b010;
  localparam logic [MISCOP_W-1:0] MISCOP_CRDTGRANT  = 3'b100;

  // ActivationOp encoding (Table 27).
  localparam logic [ACTIVATIONOP_W-1:0] ACTOP_ACTIVATE_REQ   = 4'b0000;
  localparam logic [ACTIVATIONOP_W-1:0] ACTOP_ACTIVATE_ACK   = 4'b0001;
  localparam logic [ACTIVATIONOP_W-1:0] ACTOP_DEACTIVATE_REQ = 4'b0010;
  localparam logic [ACTIVATIONOP_W-1:0] ACTOP_DEACTIVATE_ACK = 4'b0011;

  // Misc message granule counts (Tables 14, 25, 26, 18).
  localparam int MISC_GRAN        = 1;   // generic Misc / ActivationOthers (40b)
  localparam int ACTIVATEREQ_GRAN = 4;   // ActivateReq (160b, carries profiles)
  localparam int CRDTGRANT_GRAN   = 2;   // CrdtGrant   (80b)

  // --- builders -------------------------------------------------------------
  // ActivationOthers (Table 26): ActivateAck / DeactivateReq / DeactivateAck.
  //   MSGTYPE(4), MISCOP(3)=Activation, ACTIVATIONOP(4), RsvdZero(29) => 40b.
  function automatic msg_t mk_activation_other(input logic [ACTIVATIONOP_W-1:0] op);
    logic [39:0] v;
    begin
      v = {MT_MISC, MISCOP_ACTIVATION, op, 29'b0};
      mk_activation_other = {v, {(MSG_MAX_BITS-40){1'b0}}};
    end
  endfunction

  // ActivateReq (Table 25): as ActivationOthers but ACTIVATIONOP=ActivateReq
  //   plus RsvdZero(3) and RP0..RP3 Profile{ID(5),Rev(5),Opt(16)} => 160b.  The
  //   Basic Profile leaves the profile fields at 0 (Chapter 11 defines them).
  function automatic msg_t mk_activate_req(
      input logic [4:0]  rp0_id,  input logic [4:0]  rp0_rev, input logic [15:0] rp0_opt);
    logic [159:0] v;
    begin
      v = {MT_MISC, MISCOP_ACTIVATION, ACTOP_ACTIVATE_REQ, 3'b0,
           rp0_id, rp0_rev, rp0_opt, 14'b0,   // RP0
           5'b0,   5'b0,    16'b0,   14'b0,   // RP1 (not present)
           5'b0,   5'b0,    16'b0,   14'b0,   // RP2 (not present)
           5'b0,   5'b0,    16'b0};           // RP3 (not present)
      mk_activate_req = {v, {(MSG_MAX_BITS-160){1'b0}}};
    end
  endfunction

  // CrdtGrant (Table 18): bulk credit advertisement.  Only RP0 is populated in
  // this single-plane build; RP1..RP3 fields are 0.  Inputs are Table-17 codes.
  function automatic msg_t mk_crdtgrant(
      input logic [2:0] wreq0,  input logic [2:0] rreq0,
      input logic [2:0] wdata0, input logic [2:0] rdata0,
      input logic [1:0] wresp0);
    logic [79:0] v;
    begin
      v = {MT_MISC, MISCOP_CRDTGRANT,
           wreq0,  3'b0, 3'b0, 3'b0,          // WREQCRED0..3
           rreq0,  3'b0, 3'b0, 3'b0,          // RREQCRED0..3
           wdata0, 3'b0, 3'b0, 3'b0,          // WDATACRED0..3
           rdata0, 3'b0, 3'b0, 3'b0,          // RDATACRED0..3
           wresp0, 2'b0, 2'b0, 2'b0,          // WRESPCRED0..3
           17'b0};
      mk_crdtgrant = {v, {(MSG_MAX_BITS-80){1'b0}}};
    end
  endfunction

  // --- getters (MSGTYPE is get_msgtype(); these read the Misc sub-fields) ---
  function automatic logic [MISCOP_W-1:0] misc_op(input msg_t m);
    misc_op = m[MSG_MAX_BITS-1-MSGTYPE_W -: MISCOP_W];            // after MSGTYPE(4)
  endfunction
  function automatic logic [ACTIVATIONOP_W-1:0] misc_activationop(input msg_t m);
    misc_activationop = m[MSG_MAX_BITS-1-7 -: ACTIVATIONOP_W];    // after 4+3
  endfunction

  // CrdtGrant RP0 credit-code getters (offsets after MSGTYPE(4)+MISCOP(3)=7).
  function automatic logic [2:0] cg_wreq0 (input msg_t m); cg_wreq0  = m[MSG_MAX_BITS-1-7  -: 3]; endfunction
  function automatic logic [2:0] cg_rreq0 (input msg_t m); cg_rreq0  = m[MSG_MAX_BITS-1-19 -: 3]; endfunction
  function automatic logic [2:0] cg_wdata0(input msg_t m); cg_wdata0 = m[MSG_MAX_BITS-1-31 -: 3]; endfunction
  function automatic logic [2:0] cg_rdata0(input msg_t m); cg_rdata0 = m[MSG_MAX_BITS-1-43 -: 3]; endfunction
  function automatic logic [1:0] cg_wresp0(input msg_t m); cg_wresp0 = m[MSG_MAX_BITS-1-55 -: 2]; endfunction

endpackage : aou_pkg
// verilator lint_on UNUSEDSIGNAL
// verilator lint_on UNUSEDPARAM

`endif

// ==================== rtl/ucie_stream_link.sv ====================
// -----------------------------------------------------------------------------
// ucie_stream_link : one-directional flit transport across the FDI boundary.
//
// Models a UCIe streaming (FDI) link as a registered valid/ready flit channel.
// This is deliberately ABOVE the UCIe PHY / Die-to-Die Adapter: everything below
// FDI (electrical, retry, CRC, sideband) is UCIe's own concern and
// IMPLEMENTATION DEFINED per the AoU spec, so it is not modeled here.  A 1-deep
// skid buffer gives one cycle of latency, decouples the two bridges' handshakes,
// and sustains one flit per cycle.
// -----------------------------------------------------------------------------
`ifndef UCIE_STREAM_LINK_SV
`define UCIE_STREAM_LINK_SV

module ucie_stream_link #(
    parameter int W = 2000               // flit width (PLP = 250B = 2000b)
) (
    input  logic         clk,
    input  logic         rstn,
    // upstream (transmit side)
    input  logic [W-1:0] in_data,
    input  logic         in_valid,
    output logic         in_ready,
    // downstream (receive side)
    output logic [W-1:0] out_data,
    output logic         out_valid,
    input  logic         out_ready
);

  logic         full;
  logic [W-1:0] data_q;

  assign out_valid = full;
  assign out_data  = data_q;
  // can accept when empty, or when the held flit is being taken this cycle
  assign in_ready  = !full || out_ready;

  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      full   <= 1'b0;
      data_q <= '0;
    end else begin
      if (in_valid && in_ready) begin
        data_q <= in_data;
        full   <= 1'b1;
      end else if (out_valid && out_ready) begin
        full   <= 1'b0;
      end
    end
  end

endmodule
`endif

// ==================== rtl/aou_activation.sv ====================
// -----------------------------------------------------------------------------
// aou_activation : §8 interface state management + §6.4.3 reset credit exchange.
//
// Sits between a bridge's data FSM and its flit link and manages the five §8
// activity states (Table 24):
//
//   DISABLED --(ActivateReq sent/rcvd)--> ACTIVATE
//            --(ActivateAck sent&rcvd & peer CrdtGrant rcvd)--> ENABLED
//            --(DeactivateReq sent/rcvd)--> DEACTIVATE
//            --(DeactivateAck sent&rcvd)--> DISABLED (re-activates as usual)
//   any --(inconsistent Activate/Deactivate Req)--> ERROR --(err_clear)--> DISABLED
//
// While not ENABLED this module OWNS the link: it drives the bring-up / teardown
// Misc messages (ActivateReq -> ActivateAck -> CrdtGrant, and DeactivateReq ->
// DeactivateAck) and consumes the peer's, holding the data path off
// (d_tx_ready=0, d_rx_valid=0).  Once ENABLED it is a transparent pass-through.
// The peer's CrdtGrant is decoded into a one-cycle `seed` pulse that initialises
// the bridge's transmit credit counters (which reset to 0 per §8.4 DISABLED:
// "the transmitter has no credits"); `act_disabled` re-zeroes them each time the
// interface returns to DISABLED, so a later re-activation re-seeds from scratch
// (§8.2: "discards all previously received protocol-level credits").
//
// Deactivate is triggered by `deact_trig` (§8.3.2: "System Software writing a
// flag in the AoU bridge").  Only Option 1 (§8.3.2, MANDATORY) is modelled: the
// bridge asserts `deact_trig` only once the link is quiesced, so DEACTIVATE has
// no pending Data/WriteResp to drain and the module can own the link for the
// teardown handshake.  Option 2 (hardware quiescing) is a documented follow-on.
//
// ERROR (§8.3.3): entered when an inconsistent link-state Req is received (e.g.
// an ActivateReq while ENABLED, or a DeactivateReq while DISABLED).  In ERROR no
// message is transmitted and received messages are ignored (consumed/dropped);
// `err_clear` (IMPLEMENTATION_DEFINED, §8.4) returns the state to DISABLED, from
// which the interface re-initialises as usual.
//
// Ordering safety: this side only ENABLES after receiving the peer's CrdtGrant,
// which the in-order link guarantees arrives before any of the peer's data
// flits (CrdtGrant is the peer's last bring-up message).  So a data flit never
// reaches a still-activating receiver.
//
// Scope: CrdtGrant covers resource plane RP0.
// -----------------------------------------------------------------------------
`ifndef AOU_ACTIVATION_SV
`define AOU_ACTIVATION_SV

module aou_activation
  import aou_pkg::*;
#(
    // Table-17 credit codes THIS endpoint grants to the peer (for the message
    // types it receives).  Initiator grants ReadData/WriteResp; target grants
    // WriteReq/ReadReq/WriteData.  Unused types are 0.
    parameter logic [2:0] GRANT_WREQ  = 3'b000,
    parameter logic [2:0] GRANT_RREQ  = 3'b000,
    parameter logic [2:0] GRANT_WDATA = 3'b000,
    parameter logic [2:0] GRANT_RDATA = 3'b000,
    parameter logic [1:0] GRANT_WRESP = 2'b00
) (
    input  logic                clk,
    input  logic                rstn,
    output logic                enabled,           // ENABLED (data traffic ok)
    output logic                act_disabled,      // DISABLED (credit-reset qual)
    output logic                error,             // ERROR state
    input  logic                deact_trig,        // §8.3.2 SW deactivate flag
    input  logic                err_clear,         // §8.4 ERROR->DISABLED trigger
    // physical flit link (owned by this module until ENABLED)
    output logic [PLP_BITS-1:0] tx_data,
    output logic                tx_valid,
    input  logic                tx_ready,
    input  logic [PLP_BITS-1:0] rx_data,
    input  logic                rx_valid,
    output logic                rx_ready,
    // data path (bridge FSM), muxed onto the link when ENABLED
    input  logic [PLP_BITS-1:0] d_tx_data,
    input  logic                d_tx_valid,
    output logic                d_tx_ready,
    output logic [PLP_BITS-1:0] d_rx_data,
    output logic                d_rx_valid,
    input  logic                d_rx_ready,
    // credit seeding to the bridge (one-cycle pulse on peer CrdtGrant)
    output logic                seed_valid,
    output logic [2:0]          seed_wreq,
    output logic [2:0]          seed_rreq,
    output logic [2:0]          seed_wdata,
    output logic [2:0]          seed_rdata,
    output logic [1:0]          seed_wresp
);

  typedef enum logic [2:0] {
    ACT_DISABLED, ACT_ACTIVATE, ACT_ENABLED, ACT_DEACTIVATE, ACT_ERROR
  } act_e;
  act_e state;

  // activate-phase / deactivate-phase handshake flags
  logic areq_sent, areq_rcvd, aack_sent, aack_rcvd, crdt_sent, crdt_rcvd;
  logic dreq_sent, dreq_rcvd, dack_sent, dack_rcvd;

  assign enabled      = (state == ACT_ENABLED);
  assign act_disabled = (state == ACT_DISABLED);
  assign error        = (state == ACT_ERROR);

  wire in_bringup = (state == ACT_DISABLED) || (state == ACT_ACTIVATE);

  // --- bring-up / teardown TX: pick the next Misc message (priority order) ---
  wire send_areq = in_bringup && !areq_sent;
  wire send_aack = in_bringup && areq_rcvd && !aack_sent;
  wire send_crdt = in_bringup && aack_sent && !crdt_sent;
  wire send_dreq = (state == ACT_DEACTIVATE) && !dreq_sent;
  wire send_dack = (state == ACT_DEACTIVATE) && dreq_rcvd && !dack_sent;

  logic [PLP_BITS-1:0] act_tx_flit;
  logic                act_tx_valid;

  always_comb begin
    msg_t     m;
    payload_t pl;
    m            = '0;
    pl           = '0;
    act_tx_flit  = '0;
    act_tx_valid = 1'b0;
    if (send_areq) begin
      m  = mk_activate_req(5'b0, 5'b0, 16'b0);
      pl = payload_put('0, 0, ACTIVATEREQ_GRAN, m);
      act_tx_flit  = flit_assemble('0, msgstart_t'(1), pl);
      act_tx_valid = 1'b1;
    end else if (send_aack) begin
      m  = mk_activation_other(ACTOP_ACTIVATE_ACK);
      pl = payload_put('0, 0, MISC_GRAN, m);
      act_tx_flit  = flit_assemble('0, msgstart_t'(1), pl);
      act_tx_valid = 1'b1;
    end else if (send_crdt) begin
      m  = mk_crdtgrant(GRANT_WREQ, GRANT_RREQ, GRANT_WDATA, GRANT_RDATA, GRANT_WRESP);
      pl = payload_put('0, 0, CRDTGRANT_GRAN, m);
      act_tx_flit  = flit_assemble('0, msgstart_t'(1), pl);
      act_tx_valid = 1'b1;
    // teardown TX is exercised by dv/act, not the full-chain coverage harness
    // (which ties deact_trig/err_clear low) — see the coverage note at the FSM.
    // verilator coverage_off
    end else if (send_dreq) begin
      m  = mk_activation_other(ACTOP_DEACTIVATE_REQ);
      pl = payload_put('0, 0, MISC_GRAN, m);
      act_tx_flit  = flit_assemble('0, msgstart_t'(1), pl);
      act_tx_valid = 1'b1;
    end else if (send_dack) begin
      m  = mk_activation_other(ACTOP_DEACTIVATE_ACK);
      pl = payload_put('0, 0, MISC_GRAN, m);
      act_tx_flit  = flit_assemble('0, msgstart_t'(1), pl);
      act_tx_valid = 1'b1;
    end
    // verilator coverage_on
  end

  // --- RX: classify the incoming Misc message -------------------------------
  // Continuous assigns, NOT an always_comb: the message accessors do constant
  // part-selects, which under iverilog force the enclosing always_* process to
  // be "sensitive to all bits" of the wide (320b) `rm` it both writes and reads.
  // That self-referential wide process wedges iverilog's settle under cocotb's
  // VPI ReadWrite region (the pure-vvp SV TB tolerates it, cocotb does not).
  // Continuous assigns evaluate on their RHS nets directly and avoid it.
  msg_t rm;
  logic rx_misc_act, rx_is_areq, rx_is_aack, rx_is_dreq, rx_is_dack, rx_is_crdt;
  assign rm          = payload_get(flit_payload(rx_data), 0, CRDTGRANT_GRAN);
  assign rx_misc_act = (get_msgtype(rm) == MT_MISC) && (misc_op(rm) == MISCOP_ACTIVATION);
  assign rx_is_areq  = rx_misc_act && (misc_activationop(rm) == ACTOP_ACTIVATE_REQ);
  assign rx_is_aack  = rx_misc_act && (misc_activationop(rm) == ACTOP_ACTIVATE_ACK);
  assign rx_is_dreq  = rx_misc_act && (misc_activationop(rm) == ACTOP_DEACTIVATE_REQ);
  assign rx_is_dack  = rx_misc_act && (misc_activationop(rm) == ACTOP_DEACTIVATE_ACK);
  assign rx_is_crdt  = (get_msgtype(rm) == MT_MISC) && (misc_op(rm) == MISCOP_CRDTGRANT);

  // §8.3.3 inconsistent link-state Req -> ERROR.  Only the unambiguous cases are
  // flagged (ActivateReq while active, DeactivateReq while inactive); a stray
  // Ack racing a state change is tolerated rather than mis-flagged.
  wire err_now = rx_valid && (
      (rx_is_areq && ((state == ACT_ENABLED)  || (state == ACT_DEACTIVATE))) ||
      (rx_is_dreq && ((state == ACT_DISABLED) || (state == ACT_ACTIVATE))));

  // credit seed (decoded RP0 grant fields) — pulsed as the CrdtGrant is consumed
  assign seed_valid = rx_valid && !enabled && (state != ACT_ERROR) && rx_is_crdt;
  assign seed_wreq  = cg_wreq0(rm);
  assign seed_rreq  = cg_rreq0(rm);
  assign seed_wdata = cg_wdata0(rm);
  assign seed_rdata = cg_rdata0(rm);
  assign seed_wresp = cg_wresp0(rm);

  // --- link / data-path mux -------------------------------------------------
  // ERROR transmits nothing (act_tx_valid is already 0 there); every non-ENABLED
  // state consumes RX (rx_ready=1) so an ignored/dropped message never stalls.
  assign tx_data    = enabled ? d_tx_data  : act_tx_flit;
  assign tx_valid   = enabled ? d_tx_valid : act_tx_valid;
  assign d_tx_ready = enabled ? tx_ready   : 1'b0;
  assign rx_ready   = enabled ? d_rx_ready : 1'b1;
  assign d_rx_data  = rx_data;
  assign d_rx_valid = enabled ? rx_valid   : 1'b0;

  wire tx_fire = act_tx_valid && tx_ready && !enabled;

  // --- state / handshake flags ----------------------------------------------
  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      state     <= ACT_DISABLED;
      areq_sent <= 1'b0; areq_rcvd <= 1'b0;
      aack_sent <= 1'b0; aack_rcvd <= 1'b0;
      crdt_sent <= 1'b0; crdt_rcvd <= 1'b0;
      dreq_sent <= 1'b0; dreq_rcvd <= 1'b0;
      dack_sent <= 1'b0; dack_rcvd <= 1'b0;
    end else begin
      // sent-flags: which Misc message went out this cycle.
      // NOTE: the DEACTIVATE / ERROR paths below are unreachable in the
      // full-chain coverage harness (deact_trig/err_clear are tied low there)
      // and are instead verified by dv/act, so they carry `verilator
      // coverage_off` to keep the line-coverage floor meaningful.
      if (tx_fire) begin
        if      (send_areq) areq_sent <= 1'b1;
        else if (send_aack) aack_sent <= 1'b1;
        else if (send_crdt) crdt_sent <= 1'b1;
        // verilator coverage_off
        else if (send_dreq) dreq_sent <= 1'b1;
        else if (send_dack) dack_sent <= 1'b1;
        // verilator coverage_on
      end
      // received-flags (ignored entirely in ERROR)
      if (rx_valid && (state != ACT_ERROR)) begin
        if (rx_is_areq && in_bringup)                          areq_rcvd <= 1'b1;
        if (rx_is_aack && (state == ACT_ACTIVATE))             aack_rcvd <= 1'b1;
        if (rx_is_crdt && (state == ACT_ACTIVATE))             crdt_rcvd <= 1'b1;
        // verilator coverage_off
        if (rx_is_dreq && ((state == ACT_ENABLED) ||
                           (state == ACT_DEACTIVATE)))         dreq_rcvd <= 1'b1;
        if (rx_is_dack && (state == ACT_DEACTIVATE))           dack_rcvd <= 1'b1;
        // verilator coverage_on
      end
      // state transitions (registered flags; clearing on entry re-arms a phase)
      case (state)
        ACT_DISABLED:
          if ((tx_fire && send_areq) || (rx_valid && rx_is_areq))
            state <= ACT_ACTIVATE;
        ACT_ACTIVATE: begin
          // verilator coverage_off
          if (err_now) state <= ACT_ERROR;
          else
          // verilator coverage_on
          if (aack_sent && aack_rcvd && crdt_rcvd) begin
            state     <= ACT_ENABLED;
            dreq_sent <= 1'b0; dreq_rcvd <= 1'b0;   // arm a future teardown
            dack_sent <= 1'b0; dack_rcvd <= 1'b0;
          end
        end
        // The ENABLED->DEACTIVATE->DISABLED teardown and the ERROR state are
        // driven only via deact_trig / err_clear / inconsistent-Req detection,
        // none of which the full-chain coverage harness stimulates (dv/act does).
        // verilator coverage_off
        ACT_ENABLED: begin
          if (err_now) state <= ACT_ERROR;
          else if (deact_trig || (rx_valid && rx_is_dreq))
            state <= ACT_DEACTIVATE;
        end
        ACT_DEACTIVATE: begin
          if (err_now) state <= ACT_ERROR;
          else if (dack_sent && dack_rcvd) begin
            state     <= ACT_DISABLED;
            areq_sent <= 1'b0; areq_rcvd <= 1'b0;   // re-arm bring-up
            aack_sent <= 1'b0; aack_rcvd <= 1'b0;
            crdt_sent <= 1'b0; crdt_rcvd <= 1'b0;
          end
        end
        ACT_ERROR:
          if (err_clear) begin
            state     <= ACT_DISABLED;
            areq_sent <= 1'b0; areq_rcvd <= 1'b0;
            aack_sent <= 1'b0; aack_rcvd <= 1'b0;
            crdt_sent <= 1'b0; crdt_rcvd <= 1'b0;
            dreq_sent <= 1'b0; dreq_rcvd <= 1'b0;
            dack_sent <= 1'b0; dack_rcvd <= 1'b0;
          end
        default: state <= state;
        // verilator coverage_on
      endcase
    end
  end

endmodule
`endif

// ==================== rtl/axi_lite_mem.sv ====================
// -----------------------------------------------------------------------------
// axi_lite_mem : AXI4-Lite word-wide SRAM memory (the far-side target).
//
// Replaces the APB memory of ../uvm_review with a native AXI4-Lite slave, since
// AXI is the OCA non-coherent bus protocol carried over UCIe (OCA §5.2); APB is
// a low-speed peripheral bus not intended for a die-to-die link.  Reuses the
// reference's memory idioms: zero-initialised array (reads of un-written
// locations return 0), plain `always @(posedge)` write (portable to VCS, which
// rejects a second driver on an `always_ff` variable), and constant OKAY
// responses (this slave never errors).
//
//  * Data width  : DATA_W bits (default 32, word)
//  * Address     : byte address, ADDR_W bits; word index = ADDR[ADDR_W-1:2]
//  * Wait states : none (single-cycle accept + response)
//  * Responses   : BRESP/RRESP tied to OKAY
// -----------------------------------------------------------------------------
`ifndef AXI_LITE_MEM_SV
`define AXI_LITE_MEM_SV

module axi_lite_mem #(
    parameter int ADDR_W = 16,          // byte address width -> 64 KiB
    parameter int DATA_W = 32,
    parameter int STRB_W = DATA_W/8
) (
    input  logic              ACLK,
    input  logic              ARESETn,
    // write address channel
    input  logic [ADDR_W-1:0] AWADDR,
    input  logic [2:0]        AWPROT,
    input  logic              AWVALID,
    output logic              AWREADY,
    // write data channel
    input  logic [DATA_W-1:0] WDATA,
    input  logic [STRB_W-1:0] WSTRB,
    input  logic              WVALID,
    output logic              WREADY,
    // write response channel
    output logic [1:0]        BRESP,
    output logic              BVALID,
    input  logic              BREADY,
    // read address channel
    input  logic [ADDR_W-1:0] ARADDR,
    input  logic [2:0]        ARPROT,
    input  logic              ARVALID,
    output logic              ARREADY,
    // read data channel
    output logic [DATA_W-1:0] RDATA,
    output logic [1:0]        RRESP,
    output logic              RVALID,
    input  logic              RREADY
);

  localparam int WORDS = 1 << (ADDR_W-2);
  localparam logic [1:0] RESP_OKAY = 2'b00;

  // AXI requires AxPROT and full-width AxADDR on the bus, but a word memory
  // ignores protection bits and the two low (sub-word) address bits.  Sink
  // them so the (correct) "intentionally unused" lint stays visible elsewhere.
  // verilator lint_off UNUSEDSIGNAL
  wire _unused_ok = &{1'b0, AWPROT, ARPROT, AWADDR[1:0], ARADDR[1:0]};
  // verilator lint_on UNUSEDSIGNAL

  logic [DATA_W-1:0] mem [0:WORDS-1];

  // Power up all-zero so reads of un-written locations return 0 (not X).
  integer i;
  initial begin
    for (i = 0; i < WORDS; i = i + 1) mem[i] = '0;
  end

  // verilator coverage_off
  // Constant tie-offs: this slave never errors -> no logic to cover.
  assign BRESP = RESP_OKAY;
  assign RRESP = RESP_OKAY;
  // verilator coverage_on

  // --- Write channel --------------------------------------------------------
  // Capture AW and W independently, commit the write once both are held.
  logic                aw_taken, w_taken;
  logic [ADDR_W-3:0]   awaddr_q;   // captured word index (drops sub-word bits)
  logic [DATA_W-1:0]   wdata_q;
  logic [STRB_W-1:0]   wstrb_q;

  assign AWREADY = !aw_taken;
  assign WREADY  = !w_taken;

  wire do_write = aw_taken && w_taken && !BVALID;

  // plain always (not always_ff) — see header note on the memory array driver.
  always @(posedge ACLK or negedge ARESETn) begin
    if (!ARESETn) begin
      aw_taken <= 1'b0;
      w_taken  <= 1'b0;
      awaddr_q <= '0;
      wdata_q  <= '0;
      wstrb_q  <= '0;
      BVALID   <= 1'b0;
    end else begin
      if (AWVALID && AWREADY) begin
        aw_taken <= 1'b1;
        awaddr_q <= AWADDR[ADDR_W-1:2];
      end
      if (WVALID && WREADY) begin
        w_taken <= 1'b1;
        wdata_q <= WDATA;
        wstrb_q <= WSTRB;
      end
      if (do_write) begin
        // byte-strobed write into the addressed word
        for (int b = 0; b < STRB_W; b++)
          if (wstrb_q[b])
            mem[awaddr_q][b*8 +: 8] <= wdata_q[b*8 +: 8];
        aw_taken <= 1'b0;
        w_taken  <= 1'b0;
        BVALID   <= 1'b1;
      end else if (BVALID && BREADY) begin
        BVALID <= 1'b0;
      end
    end
  end

  // --- Read channel ---------------------------------------------------------
  logic ar_taken;
  assign ARREADY = !ar_taken && !RVALID;

  always @(posedge ACLK or negedge ARESETn) begin
    if (!ARESETn) begin
      ar_taken <= 1'b0;
      RVALID   <= 1'b0;
      RDATA    <= '0;
    end else begin
      if (ARVALID && ARREADY) begin
        RDATA    <= mem[ARADDR[ADDR_W-1:2]];
        RVALID   <= 1'b1;
        ar_taken <= 1'b0;   // single-cycle: data ready next cycle
      end
      if (RVALID && RREADY) begin
        RVALID <= 1'b0;
      end
    end
  end

endmodule
`endif

// ==================== rtl/aou_axi_initiator_bridge.sv ====================
// -----------------------------------------------------------------------------
// aou_axi_initiator_bridge : chiplet-A bridge (AXI4 subordinate -> AoU).
//
// Accepts AXI4 transactions (INCR/WRAP/FIXED bursts, AxLEN beats) from the TB
// master and turns them into AoU Basic-Profile messages, one message per flit:
//   * write  -> WriteReq flit, then (AWLEN+1) WriteData256 flits (one per beat)
//   * read   -> ReadReq flit; then (ARLEN+1) ReadData256 flits arrive on B->A,
//               each driven out as one R beat (RLAST on the last).
// The AoU {AW,AR}ID tag is carried and echoed back in {B,R}ID.  The burst type
// rides in the request FLEX[1:0] (AoU has no AWBURST field); address sequencing
// is done target-side, so this bridge just streams/collects beats.
//
// Multiple-outstanding (stage 2): a REQ_QD-deep request queue decouples the AXI
// AW/AR accept from the FSM, so the master can have several transactions queued
// while a prior burst is still in flight (s_awready/s_arready track queue-space,
// not FSM state).  The FSM still processes one queued request at a time and the
// single serialized link + single in-order memory return completions in issue
// order, so this is multiple-outstanding with in-order completion.
// Bursts are bounded by the data-message credit ceiling (§6): the target's
// CrdtGrant seeds enough WriteData/ReadData credits for up to CR_* granules, so
// AxLEN+1 <= CR_WDATA/WRITEDATA_GRAN beats (16 by default); longer bursts need
// mid-burst credit replenishment (follow-on).
// -----------------------------------------------------------------------------
`ifndef AOU_AXI_INITIATOR_BRIDGE_SV
`define AOU_AXI_INITIATOR_BRIDGE_SV

module aou_axi_initiator_bridge
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8,
    parameter int AXI_ID_W   = 4,
    // Multiple-outstanding request-queue depth (AXI AW/AR accepted ahead of the
    // FSM).  Depth 1 reduces to the original single-outstanding behaviour.
    parameter int REQ_QD     = 4,
    // §6 flow control — granule credits this (initiator) bridge holds to send
    // each message type it transmits.  WriteData is sized for a full burst
    // (128 granules = 16 beats) since a write burst gets no mid-burst credit
    // return (the WriteResp replenishes it at the end).
    parameter int CR_WREQ  = WRITEREQ_GRAN,     // WriteReq  credits (3 granules)
    parameter int CR_RREQ  = READREQ_GRAN,      // ReadReq   credits (3 granules)
    parameter int CR_WDATA = 128                // WriteData credits (16 beats)
) (
    input  logic                    clk,
    input  logic                    rstn,
    // ---- AXI4 subordinate (TB master drives these) ----
    input  logic [AXI_ID_W-1:0]     s_awid,
    input  logic [AXI_ADDR_W-1:0]   s_awaddr,
    input  logic [7:0]              s_awlen,
    input  logic [2:0]              s_awsize,
    input  logic [1:0]              s_awburst,
    input  logic [2:0]              s_awprot,
    input  logic                    s_awvalid,
    output logic                    s_awready,
    input  logic [AXI_DATA_W-1:0]   s_wdata,
    input  logic [AXI_STRB_W-1:0]   s_wstrb,
    input  logic                    s_wlast,
    input  logic                    s_wvalid,
    output logic                    s_wready,
    output logic [AXI_ID_W-1:0]     s_bid,
    output logic [1:0]              s_bresp,
    output logic                    s_bvalid,
    input  logic                    s_bready,
    input  logic [AXI_ID_W-1:0]     s_arid,
    input  logic [AXI_ADDR_W-1:0]   s_araddr,
    input  logic [7:0]              s_arlen,
    input  logic [2:0]              s_arsize,
    input  logic [1:0]              s_arburst,
    input  logic [2:0]              s_arprot,
    input  logic                    s_arvalid,
    output logic                    s_arready,
    output logic [AXI_ID_W-1:0]     s_rid,
    output logic [AXI_DATA_W-1:0]   s_rdata,
    output logic [1:0]              s_rresp,
    output logic                    s_rlast,
    output logic                    s_rvalid,
    input  logic                    s_rready,
    // ---- flit TX (to A->B link) ----
    output logic [PLP_BITS-1:0]     tx_data,
    output logic                    tx_valid,
    input  logic                    tx_ready,
    // ---- flit RX (from B->A link) ----
    input  logic [PLP_BITS-1:0]     rx_data,
    input  logic                    rx_valid,
    output logic                    rx_ready
);

  typedef enum logic [2:0] {
    S_IDLE, S_WREQ, S_WDATA, S_WWAIT, S_B, S_RREQ, S_RDATA
  } state_e;
  state_e state;

  // --- multiple-outstanding request queue -----------------------------------
  // Descriptors for AW/AR requests accepted from the AXI master but not yet
  // processed by the FSM.  A single write port (AW has priority over AR) keeps
  // one push per cycle; the FSM pops one descriptor per burst.
  localparam int QPW = (REQ_QD > 1) ? $clog2(REQ_QD) : 1;   // pointer width
  localparam logic [QPW-1:0] QLAST = QPW'(REQ_QD-1);        // wrap value
  logic                  q_wr    [0:REQ_QD-1];   // 1 = write, 0 = read
  logic [AXI_ID_W-1:0]   q_id    [0:REQ_QD-1];
  logic [AXI_ADDR_W-1:0] q_addr  [0:REQ_QD-1];
  logic [7:0]            q_len   [0:REQ_QD-1];
  logic [2:0]            q_size  [0:REQ_QD-1];
  logic [1:0]            q_burst [0:REQ_QD-1];
  logic [2:0]            q_prot  [0:REQ_QD-1];
  logic [QPW-1:0]        q_head, q_tail;
  logic [QPW:0]          q_count;                // 0 .. REQ_QD
  wire                   q_full  = (q_count == REQ_QD[QPW:0]);
  wire                   q_empty = (q_count == '0);

  // captured request context (one burst in flight)
  logic [AXI_ID_W-1:0]   id_q;
  logic [AXI_ADDR_W-1:0] addr_q;
  logic [7:0]            len_q;
  logic [2:0]            size_q;
  logic [1:0]            burst_q;
  logic [2:0]            prot_q;
  // write-data beat buffer
  logic [AXI_DATA_W-1:0] wdata_q;
  logic [AXI_STRB_W-1:0] wstrb_q;
  logic                  wbeat_valid, wlast_q;
  // response context
  logic [AXI_ID_W-1:0]   bid_q;
  logic [1:0]            bresp_q;

  // §6 credits HELD to transmit (granted by chiplet B).  Consumed per message,
  // replenished from the MsgCredit field of the B->A response flit.
  logic [7:0] cr_wreq, cr_rreq, cr_wdata;
  // §6 credits OWED back to B for the responses this bridge consumes
  // (ReadData / WriteResp): advertised in the next A->B flit header, then cleared.
  logic [7:0] ret_rdata, ret_wresp;

  // saturating add: cur + add, clamped at lim (§6.4 counter-saturation rule).
  function automatic logic [7:0] sat_add(input logic [7:0]  cur,
                                         input int unsigned add,
                                         input int unsigned lim);
    int unsigned s;
    begin
      s = {24'b0, cur} + add;
      sat_add = (s > lim) ? lim[7:0] : s[7:0];
    end
  endfunction

  wire wreq_ok  = (cr_wreq  >= WRITEREQ_GRAN[7:0]);
  wire wdata_ok = (cr_wdata >= WRITEDATA_GRAN[7:0]);
  wire rreq_ok  = (cr_rreq  >= READREQ_GRAN[7:0]);

  // === §8 activation + §6.4.3 reset credit exchange ========================
  // This side is the initiator: it grants ReadData/WriteResp credits to chiplet
  // B (the message types B transmits).  ReadData is sized for a full read burst.
  localparam logic [2:0] GR_RDATA = 3'b111;   // 128 granules (16 ReadData beats)
  localparam logic [1:0] GR_WRESP = 2'b01;    // >= WRITERESP_GRAN (1)

  logic                  act_enabled, act_disabled;
  logic [PLP_BITS-1:0]   dtx_data, drx_data;
  logic                  dtx_valid, dtx_ready, drx_valid, drx_ready;
  logic                  seed_valid;
  logic [2:0]            seed_wreq, seed_rreq, seed_wdata;
  // verilator lint_off UNUSEDSIGNAL
  logic [2:0]            seed_rdata;
  logic [1:0]            seed_wresp;
  logic                  act_error;
  // verilator lint_on UNUSEDSIGNAL

  aou_activation #(
    .GRANT_RDATA(GR_RDATA), .GRANT_WRESP(GR_WRESP)
  ) u_act (
    .clk(clk), .rstn(rstn), .enabled(act_enabled),
    .act_disabled(act_disabled), .error(act_error),
    .deact_trig(1'b0), .err_clear(1'b0),
    .tx_data(tx_data),  .tx_valid(tx_valid),  .tx_ready(tx_ready),
    .rx_data(rx_data),  .rx_valid(rx_valid),  .rx_ready(rx_ready),
    .d_tx_data(dtx_data), .d_tx_valid(dtx_valid), .d_tx_ready(dtx_ready),
    .d_rx_data(drx_data), .d_rx_valid(drx_valid), .d_rx_ready(drx_ready),
    .seed_valid(seed_valid), .seed_wreq(seed_wreq), .seed_rreq(seed_rreq),
    .seed_wdata(seed_wdata), .seed_rdata(seed_rdata), .seed_wresp(seed_wresp)
  );

  // MsgCredit this bridge advertises to B (grants ReadData/WriteResp).
  function automatic logic [CREDIT_W-1:0] return_credit();
    return_credit = mk_msgcredit(2'b00, 3'b000, 3'b000, 3'b000,
                                 cred_encode_ge(ret_rdata),
                                 cred_encode_ge2(ret_wresp));
  endfunction

  // --- build the outgoing flits (one message per flit) ----------------------
  function automatic flit_t build_wreq_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_writereq(2'b00, 1'b0, {{(FLEX_W-2){1'b0}}, burst_q},
                       {{(AOU_ID_W-AXI_ID_W){1'b0}}, id_q}, size_q, prot_q,
                       len_q, '0, '0,
                       {{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, addr_q});
      pl = payload_put('0, 0, WRITEREQ_GRAN, m);
      build_wreq_flit = flit_assemble_cr('0, msgstart_t'(1), return_credit(), pl);
    end
  endfunction

  function automatic flit_t build_wdata_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_writedata256(2'b00, '0,
                       {{(AOU_DATA_W-AXI_DATA_W){1'b0}}, wdata_q},
                       {{(AOU_STRB_W-AXI_STRB_W){1'b0}}, wstrb_q});
      pl = payload_put('0, 0, WRITEDATA_GRAN, m);
      build_wdata_flit = flit_assemble_cr('0, msgstart_t'(1), return_credit(), pl);
    end
  endfunction

  function automatic flit_t build_rreq_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_readreq(2'b00, 1'b0, {{(FLEX_W-2){1'b0}}, burst_q},
                      {{(AOU_ID_W-AXI_ID_W){1'b0}}, id_q}, size_q, prot_q,
                      len_q, '0, '0,
                      {{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, addr_q});
      pl = payload_put('0, 0, READREQ_GRAN, m);
      build_rreq_flit = flit_assemble_cr('0, msgstart_t'(1), return_credit(), pl);
    end
  endfunction

  // --- read-beat view of the current B->A flit ------------------------------
  msg_t rdmsg;
  // verilator lint_off UNUSEDSIGNAL
  logic [AOU_ID_W-1:0]   rd_rid_full;    // only low AXI_ID_W bits used
  logic [AOU_DATA_W-1:0] rd_full;
  // verilator lint_on UNUSEDSIGNAL
  assign rdmsg       = payload_get(flit_payload(drx_data), 0, READDATA_GRAN);
  assign rd_full     = rd_data(rdmsg);
  assign rd_rid_full = rd_id(rdmsg);

  // --- combinational outputs ------------------------------------------------
  // AXI accepted once ENABLED (§8) whenever the request queue has space; the FSM
  // pops and processes descriptors independently (multiple-outstanding accept).
  // AW has priority over AR so at most one descriptor is enqueued per cycle.
  assign s_awready = act_enabled && !q_full;
  assign s_arready = act_enabled && !q_full && !s_awvalid;  // AW priority
  wire acc_aw = s_awvalid && s_awready;
  wire acc_ar = s_arvalid && s_arready;
  wire do_pop = (state == S_IDLE) && !q_empty;
  // In S_WDATA we take a W beat only when no beat is buffered awaiting send.
  assign s_wready  = (state == S_WDATA) && !wbeat_valid;
  assign s_bid     = bid_q;
  assign s_bvalid  = (state == S_B);
  assign s_bresp   = bresp_q;
  // Drive an R beat straight from an incoming ReadData flit.
  assign s_rid     = rd_rid_full[AXI_ID_W-1:0];
  assign s_rvalid  = (state == S_RDATA) && drx_valid;
  assign s_rdata   = rd_full[AXI_DATA_W-1:0];
  assign s_rresp   = rd_resp(rdmsg);
  assign s_rlast   = rd_last(rdmsg);

  // flit TX valid: gated by the credit for the message the state emits.
  assign dtx_valid = ((state == S_WREQ)  && wreq_ok)  ||
                     ((state == S_WDATA) && wbeat_valid && wdata_ok) ||
                     ((state == S_RREQ)  && rreq_ok);
  // flit RX ready: consume a WriteResp in S_WWAIT, or a ReadData as its R beat
  // is accepted in S_RDATA.
  assign drx_ready = (state == S_WWAIT) ||
                     ((state == S_RDATA) && s_rready);

  // Build the outgoing flit procedurally (Icarus 11 wide-ufunc-in-assign issue).
  always_comb begin
    unique case (state)
      S_WREQ:  dtx_data = build_wreq_flit();
      S_WDATA: dtx_data = build_wdata_flit();
      default: dtx_data = build_rreq_flit();
    endcase
  end

  // --- FSM ------------------------------------------------------------------
  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      state    <= S_IDLE;
      q_head   <= '0; q_tail <= '0; q_count <= '0;
      id_q     <= '0; addr_q <= '0; len_q <= '0; size_q <= '0;
      burst_q  <= '0; prot_q <= '0;
      wdata_q  <= '0; wstrb_q <= '0; wbeat_valid <= 1'b0; wlast_q <= 1'b0;
      bid_q    <= '0; bresp_q <= '0;
      cr_wreq  <= '0; cr_rreq <= '0; cr_wdata <= '0;
      ret_rdata <= '0; ret_wresp <= '0;
    end else begin
      // §8.2 DISABLED: discard granted credits; §6.4.3 seed re-grants them.
      if (act_disabled) begin
        cr_wreq <= '0; cr_rreq <= '0; cr_wdata <= '0;
      end else if (seed_valid) begin
        cr_wreq  <= sat_add(cr_wreq,  cred_decode(seed_wreq),  CR_WREQ);
        cr_rreq  <= sat_add(cr_rreq,  cred_decode(seed_rreq),  CR_RREQ);
        cr_wdata <= sat_add(cr_wdata, cred_decode(seed_wdata), CR_WDATA);
      end
      // ---- request-queue push (AW priority; one push per cycle) ----
      if (acc_aw) begin
        q_wr[q_tail]   <= 1'b1;      q_id[q_tail]    <= s_awid;
        q_addr[q_tail] <= s_awaddr;  q_len[q_tail]   <= s_awlen;
        q_size[q_tail] <= s_awsize;  q_burst[q_tail] <= s_awburst;
        q_prot[q_tail] <= s_awprot;
        q_tail <= (q_tail == QLAST) ? '0 : q_tail + 1'b1;
      end else if (acc_ar) begin
        q_wr[q_tail]   <= 1'b0;      q_id[q_tail]    <= s_arid;
        q_addr[q_tail] <= s_araddr;  q_len[q_tail]   <= s_arlen;
        q_size[q_tail] <= s_arsize;  q_burst[q_tail] <= s_arburst;
        q_prot[q_tail] <= s_arprot;
        q_tail <= (q_tail == QLAST) ? '0 : q_tail + 1'b1;
      end
      if ((acc_aw || acc_ar) && !do_pop)      q_count <= q_count + 1'b1;
      else if (!(acc_aw || acc_ar) && do_pop) q_count <= q_count - 1'b1;

      unique case (state)
        // Pop the next queued request (issue order) and start its burst.
        S_IDLE: if (!q_empty) begin
          id_q    <= q_id[q_head];    addr_q  <= q_addr[q_head];
          len_q   <= q_len[q_head];   size_q  <= q_size[q_head];
          burst_q <= q_burst[q_head]; prot_q  <= q_prot[q_head];
          q_head  <= (q_head == QLAST) ? '0 : q_head + 1'b1;
          if (q_wr[q_head]) begin
            wbeat_valid <= 1'b0;
            state <= S_WREQ;
          end else begin
            state <= S_RREQ;
          end
        end
        S_WREQ: if (dtx_valid && dtx_ready) begin
          cr_wreq   <= cr_wreq - WRITEREQ_GRAN[7:0];
          ret_rdata <= '0; ret_wresp <= '0;   // return-credits just flushed
          state     <= S_WDATA;
        end
        S_WDATA: begin
          // capture a W beat when the buffer is free
          if (s_wvalid && s_wready) begin
            wdata_q <= s_wdata; wstrb_q <= s_wstrb; wlast_q <= s_wlast;
            wbeat_valid <= 1'b1;
          end
          // send the buffered beat as a WriteData flit
          if (dtx_valid && dtx_ready) begin
            wbeat_valid <= 1'b0;
            cr_wdata    <= cr_wdata - WRITEDATA_GRAN[7:0];
            if (wlast_q) state <= S_WWAIT;
          end
        end
        S_WWAIT: if (drx_valid) begin : s_wwait_blk
          msg_t                m;
          logic [CREDIT_W-1:0] mc;
          // verilator lint_off UNUSEDSIGNAL
          logic [AOU_ID_W-1:0] bidf;   // only low AXI_ID_W bits used
          // verilator lint_on UNUSEDSIGNAL
          m  = payload_get(flit_payload(drx_data), 0, WRITERESP_GRAN);
          mc = flit_credit(drx_data);
          bidf = wrsp_id(m);
          cr_wreq  <= sat_add(cr_wreq,  cred_decode(mc_wreq (mc)), CR_WREQ);
          cr_rreq  <= sat_add(cr_rreq,  cred_decode(mc_rreq (mc)), CR_RREQ);
          cr_wdata <= sat_add(cr_wdata, cred_decode(mc_wdata(mc)), CR_WDATA);
          bresp_q  <= wrsp_resp(m);
          bid_q    <= bidf[AXI_ID_W-1:0];
          ret_wresp <= ret_wresp + WRITERESP_GRAN[7:0];
          state    <= S_B;
        end
        S_B: if (s_bready) state <= S_IDLE;
        S_RREQ: if (dtx_valid && dtx_ready) begin
          cr_rreq   <= cr_rreq - READREQ_GRAN[7:0];
          ret_rdata <= '0; ret_wresp <= '0;
          state     <= S_RDATA;
        end
        S_RDATA: begin
          // credit replenish + return-credit accounting happen per accepted beat
          if (s_rvalid && s_rready) begin : s_rdata_blk
            logic [CREDIT_W-1:0] mc;
            mc = flit_credit(drx_data);
            cr_wreq  <= sat_add(cr_wreq,  cred_decode(mc_wreq (mc)), CR_WREQ);
            cr_rreq  <= sat_add(cr_rreq,  cred_decode(mc_rreq (mc)), CR_RREQ);
            cr_wdata <= sat_add(cr_wdata, cred_decode(mc_wdata(mc)), CR_WDATA);
            ret_rdata <= ret_rdata + READDATA_GRAN[7:0];
            if (rd_last(rdmsg)) state <= S_IDLE;
          end
        end
        // verilator coverage_off
        default: state <= S_IDLE;   // unreachable (all states enumerated)
        // verilator coverage_on
      endcase
    end
  end

endmodule
`endif

// ==================== rtl/aou_axi_target_bridge.sv ====================
// -----------------------------------------------------------------------------
// aou_axi_target_bridge : chiplet-B bridge (AoU -> AXI-Lite manager).
//
// Decodes AoU messages arriving on the A->B link (one message per flit) and
// drives an AXI4-Lite manager into the memory, expanding each AXI burst into a
// sequence of single-beat AXI-Lite accesses (so axi_lite_mem stays single-beat):
//   * WriteReq + (AWLEN+1) WriteData -> AWLEN+1 single-beat writes -> WriteResp
//   * ReadReq -> AWLEN+1 single-beat reads -> AWLEN+1 ReadData (RLAST on last)
// Per-beat addresses follow the AXI burst type (INCR/WRAP/FIXED) carried in the
// request (burst type in FLEX[1:0]); the {AW,AR}ID tag is echoed into {B,R}ID.
//
// Single-outstanding (one burst in flight), matching the initiator bridge.
// -----------------------------------------------------------------------------
`ifndef AOU_AXI_TARGET_BRIDGE_SV
`define AOU_AXI_TARGET_BRIDGE_SV

module aou_axi_target_bridge
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8,
    parameter int AXI_ID_W   = 4,
    // §6 flow control — granule credits this (target) bridge holds to send each
    // response message type (granted by chiplet A).  ReadData is sized for a
    // full read burst (128 granules = 16 beats).
    parameter int CR_RDATA = 128,               // ReadData  credits (16 beats)
    parameter int CR_WRESP = WRITERESP_GRAN     // WriteResp credits (1 granule)
) (
    input  logic                    clk,
    input  logic                    rstn,
    // ---- flit RX (from A->B link) ----
    input  logic [PLP_BITS-1:0]     rx_data,
    input  logic                    rx_valid,
    output logic                    rx_ready,
    // ---- flit TX (to B->A link) ----
    output logic [PLP_BITS-1:0]     tx_data,
    output logic                    tx_valid,
    input  logic                    tx_ready,
    // ---- AXI4-Lite manager (drives the memory) ----
    output logic [AXI_ADDR_W-1:0]   m_awaddr,
    output logic [2:0]              m_awprot,
    output logic                    m_awvalid,
    input  logic                    m_awready,
    output logic [AXI_DATA_W-1:0]   m_wdata,
    output logic [AXI_STRB_W-1:0]   m_wstrb,
    output logic                    m_wvalid,
    input  logic                    m_wready,
    input  logic [1:0]              m_bresp,
    input  logic                    m_bvalid,
    output logic                    m_bready,
    output logic [AXI_ADDR_W-1:0]   m_araddr,
    output logic [2:0]              m_arprot,
    output logic                    m_arvalid,
    input  logic                    m_arready,
    input  logic [AXI_DATA_W-1:0]   m_rdata,
    input  logic [1:0]              m_rresp,
    input  logic                    m_rvalid,
    output logic                    m_rready
);

  typedef enum logic [2:0] {
    S_IDLE, S_WBEAT, S_WRESP, S_RBEAT
  } state_e;
  state_e state;

  // burst context
  logic [AXI_ID_W-1:0]   id_q;
  logic [AXI_ADDR_W-1:0] base_q, addr_q;   // start address, current beat address
  logic [7:0]            len_q, beat_q;    // AxLEN, current beat index
  logic [2:0]            size_q;
  logic [1:0]            burst_q;
  // write-beat buffer + mem-write handshake
  logic [AXI_DATA_W-1:0] wdata_q;
  logic [AXI_STRB_W-1:0] wstrb_q;
  logic                  wpending, aw_done, w_done;
  logic [1:0]            bresp_q;
  // read-beat buffer + mem-read handshake
  logic [AXI_DATA_W-1:0] rdata_q;
  logic [1:0]            rresp_q;
  logic                  rpending, ar_done;

  // §6 credits HELD to transmit responses (granted by chiplet A).
  logic [7:0] cr_rdata, cr_wresp;
  // §6 credits OWED back to A for the request messages this bridge consumes.
  logic [7:0] ret_wreq, ret_rreq, ret_wdata;

  function automatic logic [7:0] sat_add(input logic [7:0]  cur,
                                         input int unsigned add,
                                         input int unsigned lim);
    int unsigned s;
    begin
      s = {24'b0, cur} + add;
      sat_add = (s > lim) ? lim[7:0] : s[7:0];
    end
  endfunction

  // next-beat address (INCR/WRAP/FIXED), computed in the AoU 64b address space.
  function automatic logic [AXI_ADDR_W-1:0] next_addr();
    // verilator lint_off UNUSEDSIGNAL
    logic [AOU_ADDR_W-1:0] n;         // only low AXI_ADDR_W bits used
    // verilator lint_on UNUSEDSIGNAL
    begin
      n = axi_burst_next({{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, addr_q},
                         {{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, base_q},
                         burst_q, size_q, len_q);
      next_addr = n[AXI_ADDR_W-1:0];
    end
  endfunction

  wire last_beat = (beat_q == len_q);

  // === §8 activation + §6.4.3 reset credit exchange ========================
  localparam logic [2:0] GR_WREQ  = 3'b010;   // >= WRITEREQ_GRAN  (3)
  localparam logic [2:0] GR_RREQ  = 3'b010;   // >= READREQ_GRAN   (3)
  localparam logic [2:0] GR_WDATA = 3'b111;   // 128 granules (16 WriteData beats)

  logic [PLP_BITS-1:0]   dtx_data, drx_data;
  logic                  dtx_valid, dtx_ready, drx_valid, drx_ready;
  logic                  seed_valid, act_disabled;
  logic [2:0]            seed_rdata;
  logic [1:0]            seed_wresp;
  // verilator lint_off UNUSEDSIGNAL
  logic                  act_enabled, act_error;
  logic [2:0]            seed_wreq, seed_rreq, seed_wdata;
  // verilator lint_on UNUSEDSIGNAL

  aou_activation #(
    .GRANT_WREQ(GR_WREQ), .GRANT_RREQ(GR_RREQ), .GRANT_WDATA(GR_WDATA)
  ) u_act (
    .clk(clk), .rstn(rstn), .enabled(act_enabled),
    .act_disabled(act_disabled), .error(act_error),
    .deact_trig(1'b0), .err_clear(1'b0),
    .tx_data(tx_data),  .tx_valid(tx_valid),  .tx_ready(tx_ready),
    .rx_data(rx_data),  .rx_valid(rx_valid),  .rx_ready(rx_ready),
    .d_tx_data(dtx_data), .d_tx_valid(dtx_valid), .d_tx_ready(dtx_ready),
    .d_rx_data(drx_data), .d_rx_valid(drx_valid), .d_rx_ready(drx_ready),
    .seed_valid(seed_valid), .seed_wreq(seed_wreq), .seed_rreq(seed_rreq),
    .seed_wdata(seed_wdata), .seed_rdata(seed_rdata), .seed_wresp(seed_wresp)
  );

  // MsgCredit this bridge advertises to A (grants WriteReq/ReadReq/WriteData).
  function automatic logic [CREDIT_W-1:0] return_credit();
    return_credit = mk_msgcredit(2'b00,
                                 cred_encode_ge(ret_wreq),
                                 cred_encode_ge(ret_rreq),
                                 cred_encode_ge(ret_wdata),
                                 3'b000, 2'b00);
  endfunction

  // --- build the response flits ---------------------------------------------
  function automatic flit_t build_wresp_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_writeresp(2'b00, '0, {{(AOU_ID_W-AXI_ID_W){1'b0}}, id_q}, bresp_q);
      pl = payload_put('0, 0, WRITERESP_GRAN, m);
      build_wresp_flit = flit_assemble_cr('0, msgstart_t'(1), return_credit(), pl);
    end
  endfunction

  function automatic flit_t build_rdata_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_readdata256(2'b00, '0, {{(AOU_ID_W-AXI_ID_W){1'b0}}, id_q},
                          rresp_q, last_beat,
                          {{(AOU_DATA_W-AXI_DATA_W){1'b0}}, rdata_q});
      pl = payload_put('0, 0, READDATA_GRAN, m);
      build_rdata_flit = flit_assemble_cr('0, msgstart_t'(1), return_credit(), pl);
    end
  endfunction

  // --- incoming-flit views (one message per flit, always at granule 0) ------
  payload_t                in_pl;
  logic [MSGTYPE_W-1:0]    in_mt;
  msg_t                    in_msg;
  // verilator lint_off UNUSEDSIGNAL
  logic [AOU_ID_W-1:0]    in_id;      // only low AXI_ID_W bits used
  logic [AOU_ADDR_W-1:0]  in_addr;
  logic [AOU_DATA_W-1:0]  in_wdata;
  logic [AOU_STRB_W-1:0]  in_wstrb;
  // verilator lint_on UNUSEDSIGNAL
  assign in_pl    = flit_payload(drx_data);
  assign in_mt    = payload_msgtype(in_pl, 0);
  assign in_msg   = payload_get(in_pl, 0, WRITEDATA_GRAN);  // widest; req uses top bits
  assign in_addr  = (in_mt == MT_WRITEREQ) ? wr_addr(in_msg) : rr_addr(in_msg);
  assign in_id    = (in_mt == MT_WRITEREQ) ? wr_id(in_msg)   : rr_id(in_msg);
  assign in_wdata = wd_data(in_msg);
  assign in_wstrb = wd_strb(in_msg);

  // --- combinational outputs ------------------------------------------------
  // consume the request in S_IDLE; consume a WriteData beat into the buffer in
  // S_WBEAT when the buffer is free.
  assign drx_ready = (state == S_IDLE) || ((state == S_WBEAT) && !wpending);
  assign m_awaddr  = addr_q;
  assign m_awprot  = 3'b000;
  assign m_awvalid = (state == S_WBEAT) && wpending && !aw_done;
  assign m_wdata   = wdata_q;
  assign m_wstrb   = wstrb_q;
  assign m_wvalid  = (state == S_WBEAT) && wpending && !w_done;
  assign m_bready  = (state == S_WBEAT) && wpending;
  assign m_araddr  = addr_q;
  assign m_arprot  = 3'b000;
  assign m_arvalid = (state == S_RBEAT) && !rpending && !ar_done;
  assign m_rready  = (state == S_RBEAT) && !rpending;
  // response send gated by credit (§6.1)
  assign dtx_valid = ((state == S_WRESP) && (cr_wresp >= WRITERESP_GRAN[7:0])) ||
                     ((state == S_RBEAT) && rpending && (cr_rdata >= READDATA_GRAN[7:0]));

  always_comb begin
    if (state == S_WRESP) dtx_data = build_wresp_flit();
    else                  dtx_data = build_rdata_flit();
  end

  // --- FSM ------------------------------------------------------------------
  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      state    <= S_IDLE;
      id_q     <= '0; base_q <= '0; addr_q <= '0;
      len_q    <= '0; beat_q <= '0; size_q <= '0; burst_q <= '0;
      wdata_q  <= '0; wstrb_q <= '0; wpending <= 1'b0;
      aw_done  <= 1'b0; w_done <= 1'b0; bresp_q <= '0;
      rdata_q  <= '0; rresp_q <= '0; rpending <= 1'b0; ar_done <= 1'b0;
      cr_rdata <= '0; cr_wresp <= '0;
      ret_wreq <= '0; ret_rreq <= '0; ret_wdata <= '0;
    end else begin
      // §8.2 DISABLED: discard granted credits; §6.4.3 seed re-grants them.
      if (act_disabled) begin
        cr_rdata <= '0; cr_wresp <= '0;
      end else if (seed_valid) begin
        cr_rdata <= sat_add(cr_rdata, cred_decode(seed_rdata),         CR_RDATA);
        cr_wresp <= sat_add(cr_wresp, cred_decode({1'b0, seed_wresp}), CR_WRESP);
      end
      unique case (state)
        S_IDLE: if (drx_valid) begin : s_idle_blk
          logic [CREDIT_W-1:0] mc;
          mc = flit_credit(drx_data);
          cr_rdata <= sat_add(cr_rdata, cred_decode(mc_rdata(mc)),          CR_RDATA);
          cr_wresp <= sat_add(cr_wresp, cred_decode({1'b0, mc_wresp(mc)}), CR_WRESP);
          id_q    <= in_id[AXI_ID_W-1:0];
          base_q  <= in_addr[AXI_ADDR_W-1:0];
          addr_q  <= in_addr[AXI_ADDR_W-1:0];
          beat_q  <= '0;
          if (in_mt == MT_WRITEREQ) begin
            len_q   <= wr_len(in_msg);
            size_q  <= wr_size(in_msg);
            burst_q <= wr_burst(in_msg);
            wpending <= 1'b0; aw_done <= 1'b0; w_done <= 1'b0;
            ret_wreq <= ret_wreq + WRITEREQ_GRAN[7:0];
            state   <= S_WBEAT;
          end else begin
            len_q   <= rr_len(in_msg);
            size_q  <= rr_size(in_msg);
            burst_q <= rr_burst(in_msg);
            rpending <= 1'b0; ar_done <= 1'b0;
            ret_rreq <= ret_rreq + READREQ_GRAN[7:0];
            state   <= S_RBEAT;
          end
        end
        S_WBEAT: begin
          // buffer a WriteData beat
          if (drx_valid && drx_ready && !wpending) begin
            wdata_q <= in_wdata[AXI_DATA_W-1:0];
            wstrb_q <= in_wstrb[AXI_STRB_W-1:0];
            wpending <= 1'b1; aw_done <= 1'b0; w_done <= 1'b0;
            ret_wdata <= ret_wdata + WRITEDATA_GRAN[7:0];
          end
          // single-beat memory write
          if (m_awvalid && m_awready) aw_done <= 1'b1;
          if (m_wvalid  && m_wready ) w_done  <= 1'b1;
          if (m_bvalid  && m_bready ) begin
            bresp_q  <= m_bresp;
            wpending <= 1'b0;
            addr_q   <= next_addr();
            beat_q   <= beat_q + 8'd1;
            if (last_beat) state <= S_WRESP;
          end
        end
        S_WRESP: if (dtx_valid && dtx_ready) begin
          cr_wresp  <= cr_wresp - WRITERESP_GRAN[7:0];
          ret_wreq  <= '0; ret_rreq <= '0; ret_wdata <= '0;
          state     <= S_IDLE;
        end
        S_RBEAT: begin
          // single-beat memory read into the buffer
          if (m_arvalid && m_arready) ar_done <= 1'b1;
          if (m_rvalid  && m_rready ) begin
            rdata_q  <= m_rdata;
            rresp_q  <= m_rresp;
            rpending <= 1'b1;
          end
          // send the buffered beat as a ReadData flit
          if (dtx_valid && dtx_ready) begin
            cr_rdata <= cr_rdata - READDATA_GRAN[7:0];
            rpending <= 1'b0; ar_done <= 1'b0;
            addr_q   <= next_addr();
            beat_q   <= beat_q + 8'd1;
            if (last_beat) begin
              ret_wreq <= '0; ret_rreq <= '0; ret_wdata <= '0;
              state    <= S_IDLE;
            end
          end
        end
        // verilator coverage_off
        default: state <= S_IDLE;   // unreachable (all states enumerated)
        // verilator coverage_on
      endcase
    end
  end

endmodule
`endif

// ==================== rtl/axi_ucie_mem_top.sv ====================
// -----------------------------------------------------------------------------
// axi_ucie_mem_top : DUT top — AXI-Lite over UCIe (AoU) to an AXI-Lite memory.
//
//   TB AXI-Lite master
//        -> aou_axi_initiator_bridge  (chiplet A: AXI-Lite SUB -> AoU flits)
//        == ucie_stream_link A->B ==>
//        -> aou_axi_target_bridge     (chiplet B: AoU flits -> AXI-Lite MGR)
//        -> axi_lite_mem              (the memory)
//        <= ucie_stream_link B->A <=  (WriteResp / ReadData flits)
//
// Flat AXI-Lite ports on the boundary (no SystemVerilog interface) so the same
// DUT is drivable from cocotb, a portable SV TB, a Verilator SystemC harness,
// and UVM without wrapper shims.
// -----------------------------------------------------------------------------
`ifndef AXI_UCIE_MEM_TOP_SV
`define AXI_UCIE_MEM_TOP_SV

module axi_ucie_mem_top
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8,
    parameter int AXI_ID_W   = 4,
    parameter int MEM_ADDR_W = 16          // memory byte-address width (64 KiB)
) (
    input  logic                  ACLK,
    input  logic                  ARESETn,
    // AXI4 subordinate (TB master side) — INCR/WRAP/FIXED bursts, AxLEN beats
    input  logic [AXI_ID_W-1:0]   AWID,
    input  logic [AXI_ADDR_W-1:0] AWADDR,
    input  logic [7:0]            AWLEN,
    input  logic [2:0]            AWSIZE,
    input  logic [1:0]            AWBURST,
    input  logic [2:0]            AWPROT,
    input  logic                  AWVALID,
    output logic                  AWREADY,
    input  logic [AXI_DATA_W-1:0] WDATA,
    input  logic [AXI_STRB_W-1:0] WSTRB,
    input  logic                  WLAST,
    input  logic                  WVALID,
    output logic                  WREADY,
    output logic [AXI_ID_W-1:0]   BID,
    output logic [1:0]            BRESP,
    output logic                  BVALID,
    input  logic                  BREADY,
    input  logic [AXI_ID_W-1:0]   ARID,
    input  logic [AXI_ADDR_W-1:0] ARADDR,
    input  logic [7:0]            ARLEN,
    input  logic [2:0]            ARSIZE,
    input  logic [1:0]            ARBURST,
    input  logic [2:0]            ARPROT,
    input  logic                  ARVALID,
    output logic                  ARREADY,
    output logic [AXI_ID_W-1:0]   RID,
    output logic [AXI_DATA_W-1:0] RDATA,
    output logic [1:0]            RRESP,
    output logic                  RLAST,
    output logic                  RVALID,
    input  logic                  RREADY
);

  // --- flit links (both directions) -----------------------------------------
  logic [PLP_BITS-1:0] a2b_data, b2a_data;
  logic                a2b_valid, a2b_ready, b2a_valid, b2a_ready;

  // initiator side of each link (as seen by the initiator bridge)
  logic [PLP_BITS-1:0] init_tx_data, init_rx_data;
  logic                init_tx_valid, init_tx_ready, init_rx_valid, init_rx_ready;
  // target side of each link
  logic [PLP_BITS-1:0] tgt_tx_data, tgt_rx_data;
  logic                tgt_tx_valid, tgt_tx_ready, tgt_rx_valid, tgt_rx_ready;

  // --- chiplet-B AXI-Lite manager <-> memory --------------------------------
  logic [AXI_ADDR_W-1:0] m_awaddr, m_araddr;
  logic [2:0]            m_awprot, m_arprot;
  logic                  m_awvalid, m_awready, m_wvalid, m_wready;
  logic [AXI_DATA_W-1:0] m_wdata, m_rdata;
  logic [AXI_STRB_W-1:0] m_wstrb;
  logic [1:0]            m_bresp, m_rresp;
  logic                  m_bvalid, m_bready, m_arvalid, m_arready, m_rvalid, m_rready;

  // === Chiplet A: initiator bridge =========================================
  aou_axi_initiator_bridge #(
    .AXI_ADDR_W(AXI_ADDR_W), .AXI_DATA_W(AXI_DATA_W), .AXI_STRB_W(AXI_STRB_W),
    .AXI_ID_W(AXI_ID_W)
  ) u_init (
    .clk(ACLK), .rstn(ARESETn),
    .s_awid(AWID), .s_awaddr(AWADDR), .s_awlen(AWLEN), .s_awsize(AWSIZE),
    .s_awburst(AWBURST), .s_awprot(AWPROT), .s_awvalid(AWVALID), .s_awready(AWREADY),
    .s_wdata(WDATA), .s_wstrb(WSTRB), .s_wlast(WLAST), .s_wvalid(WVALID), .s_wready(WREADY),
    .s_bid(BID), .s_bresp(BRESP), .s_bvalid(BVALID), .s_bready(BREADY),
    .s_arid(ARID), .s_araddr(ARADDR), .s_arlen(ARLEN), .s_arsize(ARSIZE),
    .s_arburst(ARBURST), .s_arprot(ARPROT), .s_arvalid(ARVALID), .s_arready(ARREADY),
    .s_rid(RID), .s_rdata(RDATA), .s_rresp(RRESP), .s_rlast(RLAST),
    .s_rvalid(RVALID), .s_rready(RREADY),
    .tx_data(init_tx_data), .tx_valid(init_tx_valid), .tx_ready(init_tx_ready),
    .rx_data(init_rx_data), .rx_valid(init_rx_valid), .rx_ready(init_rx_ready)
  );

  // === A->B link ============================================================
  ucie_stream_link #(.W(PLP_BITS)) u_link_a2b (
    .clk(ACLK), .rstn(ARESETn),
    .in_data(init_tx_data), .in_valid(init_tx_valid), .in_ready(init_tx_ready),
    .out_data(a2b_data),    .out_valid(a2b_valid),    .out_ready(a2b_ready)
  );
  assign tgt_rx_data  = a2b_data;
  assign tgt_rx_valid = a2b_valid;
  assign a2b_ready    = tgt_rx_ready;

  // === B->A link ============================================================
  ucie_stream_link #(.W(PLP_BITS)) u_link_b2a (
    .clk(ACLK), .rstn(ARESETn),
    .in_data(tgt_tx_data), .in_valid(tgt_tx_valid), .in_ready(tgt_tx_ready),
    .out_data(b2a_data),   .out_valid(b2a_valid),   .out_ready(b2a_ready)
  );
  assign init_rx_data  = b2a_data;
  assign init_rx_valid = b2a_valid;
  assign b2a_ready     = init_rx_ready;

  // === Chiplet B: target bridge ============================================
  aou_axi_target_bridge #(
    .AXI_ADDR_W(AXI_ADDR_W), .AXI_DATA_W(AXI_DATA_W), .AXI_STRB_W(AXI_STRB_W),
    .AXI_ID_W(AXI_ID_W)
  ) u_tgt (
    .clk(ACLK), .rstn(ARESETn),
    .rx_data(tgt_rx_data), .rx_valid(tgt_rx_valid), .rx_ready(tgt_rx_ready),
    .tx_data(tgt_tx_data), .tx_valid(tgt_tx_valid), .tx_ready(tgt_tx_ready),
    .m_awaddr(m_awaddr), .m_awprot(m_awprot), .m_awvalid(m_awvalid), .m_awready(m_awready),
    .m_wdata(m_wdata),   .m_wstrb(m_wstrb),   .m_wvalid(m_wvalid),   .m_wready(m_wready),
    .m_bresp(m_bresp),   .m_bvalid(m_bvalid), .m_bready(m_bready),
    .m_araddr(m_araddr), .m_arprot(m_arprot), .m_arvalid(m_arvalid), .m_arready(m_arready),
    .m_rdata(m_rdata),   .m_rresp(m_rresp),   .m_rvalid(m_rvalid),   .m_rready(m_rready)
  );

  // === Chiplet B: AXI-Lite memory ==========================================
  axi_lite_mem #(
    .ADDR_W(MEM_ADDR_W), .DATA_W(AXI_DATA_W), .STRB_W(AXI_STRB_W)
  ) u_mem (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .AWADDR(m_awaddr[MEM_ADDR_W-1:0]), .AWPROT(m_awprot), .AWVALID(m_awvalid), .AWREADY(m_awready),
    .WDATA(m_wdata), .WSTRB(m_wstrb), .WVALID(m_wvalid), .WREADY(m_wready),
    .BRESP(m_bresp), .BVALID(m_bvalid), .BREADY(m_bready),
    .ARADDR(m_araddr[MEM_ADDR_W-1:0]), .ARPROT(m_arprot), .ARVALID(m_arvalid), .ARREADY(m_arready),
    .RDATA(m_rdata), .RRESP(m_rresp), .RVALID(m_rvalid), .RREADY(m_rready)
  );

  // upper address bits beyond the memory are not decoded (single memory target)
  // verilator lint_off UNUSEDSIGNAL
  wire _unused_ok = &{1'b0, m_awaddr[AXI_ADDR_W-1:MEM_ADDR_W],
                            m_araddr[AXI_ADDR_W-1:MEM_ADDR_W]};
  // verilator lint_on UNUSEDSIGNAL

endmodule
`endif
