// =============================================================================
// design.sv  —  AXI-Lite-over-UCIe (AoU) to AXI-Lite memory : full DUT RTL.
//
// AUTO-GENERATED by 'make -C uvm eda' — do not edit by hand.  Regenerate after
// any rtl/ change.  Concatenation of rtl/*.sv (package first, then leaf modules,
// then the top), for the EDA Playground DESIGN pane; pair with testbench.sv.
// =============================================================================

// ==================== rtl/aou_pkg.sv ====================
// -----------------------------------------------------------------------------
// aou_pkg : AXI-over-UCIe (AoU) Basic-Profile message + flit definitions.
//
// Source: "AXI over UCIe Protocol Specification v0.8" (OCA / Tenstorrent),
//   Chapter 4 (Packing) and Chapter 5 (Message Structures).
//
// Scope of THIS package (see docs/PLAN.md):
//   * Basic Profile messages: WriteReq, ReadReq, WriteData(256b),
//     ReadData(256b), WriteResp.  (WriteDataFull / 512b / 1024b not built.)
//   * Resource Plane RP0 only; no credit flow control; no activation FSM.
//   * AXI4-Lite front door, 32-bit data / 32-bit address, single beat
//     (AWLEN=ARLEN=0, DLENGTH=00 -> 256b data message).
//
// Bit-ordering convention (documented, shared by packer + unpacker):
//   * A message is packed MSB-first in spec table order (Tables 2,3,4,10,13):
//     the first table field lands in the most-significant bits.
//   * Each message is left-justified in an MSG_MAX_BITS (=320b) vector, so
//     message granule 0 is always the MSB slice [319:280].
//   * The 240B PLP payload is NUM_GRAN granules of GRAN_BITS bits each, granule
//     0 = most-significant.  A message of N granules starting at granule g
//     occupies payload[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: N*GRAN_BITS].
//   Field *widths* and *granule counts* match the spec exactly; the exact §5.8
//   PCIe byte placement within a granule is modeled at field granularity (it is
//   not needed for interoperability inside this self-contained design).
// -----------------------------------------------------------------------------
`ifndef AOU_PKG_SV
`define AOU_PKG_SV

// This is a protocol-definition package: it deliberately declares the full
// Basic-Profile field set (including reserved fields and the 512b/1024b DLENGTH
// encodings this build does not yet use), and its field getters each read only
// the slice of a message they need.  Both are intentional, so waive the
// "unused" lints that would otherwise fire on the package in isolation.
// verilator lint_off UNUSEDPARAM
// verilator lint_off UNUSEDSIGNAL
package aou_pkg;

  // --- Flit / PLP geometry (spec §4.2) --------------------------------------
  localparam int GRAN_BITS         = 40;                 // 5 bytes per granule
  localparam int NUM_GRAN          = 48;                 // 240B payload / 5B
  localparam int PLP_PAYLOAD_BITS  = GRAN_BITS * NUM_GRAN; // 1920
  localparam int PLP_HDR_BITS      = 80;                 // 10B protocol header
  localparam int PLP_BITS          = PLP_HDR_BITS + PLP_PAYLOAD_BITS; // 2000 (250B)

  localparam int FDID_W  = 2;                           // Flit Destination ID
  localparam int CREDIT_W = 16;                          // MsgCredit field
  localparam int HDR_RSVD_W = PLP_HDR_BITS - FDID_W - NUM_GRAN - CREDIT_W; // 14

  typedef logic [PLP_BITS-1:0]         flit_t;           // 250B PLP == link word
  typedef logic [PLP_PAYLOAD_BITS-1:0] payload_t;        // 240B / 48 granules
  typedef logic [NUM_GRAN-1:0]         msgstart_t;       // MsgStart bitmap

  // --- MSGTYPE encoding (spec Table 1) --------------------------------------
  localparam int MSGTYPE_W = 4;
  typedef enum logic [MSGTYPE_W-1:0] {
    MT_MISC          = 4'b0000,
    MT_WRITEREQ      = 4'b0001,
    MT_READREQ       = 4'b0010,
    MT_WRITEDATA     = 4'b0011,
    MT_READDATA      = 4'b0100,
    MT_WRITERESP     = 4'b0101,
    MT_WRITEDATAFULL = 4'b0110
  } msgtype_e;

  // --- AoU-specific + AXI-equivalent field widths (Basic Profile) -----------
  localparam int RP_W      = 2;    // resource plane
  localparam int DLENGTH_W = 2;    // data-message width selector
  localparam int FLEX_W    = 16;   // USER[15:0] in Basic Profile
  localparam int AOU_ID_W  = 10;   // AWID/ARID/BID/RID
  localparam int AOU_SIZE_W  = 3;
  localparam int AOU_PROT_W  = 3;
  localparam int AOU_LEN_W   = 8;
  localparam int AOU_CACHE_W = 4;
  localparam int AOU_QOS_W   = 4;
  localparam int AOU_ADDR_W  = 64;
  localparam int AOU_DATA_W  = 256;  // WriteData/ReadData(256b)
  localparam int AOU_STRB_W  = 32;
  localparam int AOU_RESP_W  = 2;    // RRESP/BRESP

  // DLENGTH encodings (spec §5.4).  This design uses 256b only.
  localparam logic [DLENGTH_W-1:0] DLEN_256  = 2'b00;
  localparam logic [DLENGTH_W-1:0] DLEN_512  = 2'b01;
  localparam logic [DLENGTH_W-1:0] DLEN_1024 = 2'b10;

  // --- Message bit-lengths and granule counts (spec §5.3-5.5) ---------------
  localparam int WRITEREQ_BITS  = 120; localparam int WRITEREQ_GRAN  = 3;
  localparam int READREQ_BITS   = 120; localparam int READREQ_GRAN   = 3;
  localparam int WRITEDATA_BITS = 320; localparam int WRITEDATA_GRAN = 8;
  localparam int READDATA_BITS  = 320; localparam int READDATA_GRAN  = 8;
  localparam int WRITERESP_BITS = 40;  localparam int WRITERESP_GRAN = 1;

  localparam int MSG_MAX_BITS = 320;   // largest built message (WriteData256)
  localparam int MSG_MAX_GRAN = 8;

  typedef logic [MSG_MAX_BITS-1:0] msg_t;   // left-justified message container

  // granule count for a decoded MSGTYPE (0 = unknown/unsupported)
  function automatic int msg_granules(input logic [MSGTYPE_W-1:0] mt);
    case (mt)
      MT_WRITEREQ  : msg_granules = WRITEREQ_GRAN;
      MT_READREQ   : msg_granules = READREQ_GRAN;
      MT_WRITEDATA : msg_granules = WRITEDATA_GRAN;
      MT_READDATA  : msg_granules = READDATA_GRAN;
      MT_WRITERESP : msg_granules = WRITERESP_GRAN;
      default      : msg_granules = 0;
    endcase
  endfunction

  // =========================================================================
  // Message builders.  Each returns an MSG_MAX_BITS vector with the message
  // left-justified (granule 0 in the MSBs) and low bits zero-padded.
  // AXI-Lite fields are widened into the AoU fields (addr/data zero-extended,
  // id placed in the low bits of the 10-bit AoU id field).
  // =========================================================================

  // WriteReq (Table 2): MSGTYPE,RP,RsvdZero(1),AWLOCK,FLEX,AWID,AWSIZE,AWPROT,
  //                     AWLEN,AWCACHE,AWQOS,AWADDR  => 120b
  function automatic msg_t mk_writereq(
      input logic [RP_W-1:0]        rp,
      input logic                   awlock,
      input logic [FLEX_W-1:0]      flex,
      input logic [AOU_ID_W-1:0]    awid,
      input logic [AOU_SIZE_W-1:0]  awsize,
      input logic [AOU_PROT_W-1:0]  awprot,
      input logic [AOU_LEN_W-1:0]   awlen,
      input logic [AOU_CACHE_W-1:0] awcache,
      input logic [AOU_QOS_W-1:0]   awqos,
      input logic [AOU_ADDR_W-1:0]  awaddr);
    logic [WRITEREQ_BITS-1:0] v;
    begin
      v = {MT_WRITEREQ, rp, 1'b0, awlock, flex, awid, awsize, awprot,
           awlen, awcache, awqos, awaddr};
      mk_writereq = {v, {(MSG_MAX_BITS-WRITEREQ_BITS){1'b0}}};
    end
  endfunction

  // ReadReq (Table 3): symmetric to WriteReq => 120b
  function automatic msg_t mk_readreq(
      input logic [RP_W-1:0]        rp,
      input logic                   arlock,
      input logic [FLEX_W-1:0]      flex,
      input logic [AOU_ID_W-1:0]    arid,
      input logic [AOU_SIZE_W-1:0]  arsize,
      input logic [AOU_PROT_W-1:0]  arprot,
      input logic [AOU_LEN_W-1:0]   arlen,
      input logic [AOU_CACHE_W-1:0] arcache,
      input logic [AOU_QOS_W-1:0]   arqos,
      input logic [AOU_ADDR_W-1:0]  araddr);
    logic [READREQ_BITS-1:0] v;
    begin
      v = {MT_READREQ, rp, 1'b0, arlock, flex, arid, arsize, arprot,
           arlen, arcache, arqos, araddr};
      mk_readreq = {v, {(MSG_MAX_BITS-READREQ_BITS){1'b0}}};
    end
  endfunction

  // WriteData 256b (Table 4): MSGTYPE,RP,DLENGTH,FLEX,WDATA(256),WSTRB(32),
  //                           RsvdZero(8) => 320b (exactly MSG_MAX_BITS)
  function automatic msg_t mk_writedata256(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_DATA_W-1:0] wdata,
      input logic [AOU_STRB_W-1:0] wstrb);
    mk_writedata256 = {MT_WRITEDATA, rp, DLEN_256, flex, wdata, wstrb, 8'b0};
  endfunction

  // ReadData 256b (Table 10): MSGTYPE,RP,DLENGTH,FLEX,RID,RRESP,RLAST,
  //   RsvdZero(3),RDATA(256),RsvdZero(24) => 320b
  function automatic msg_t mk_readdata256(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_ID_W-1:0]   rid,
      input logic [AOU_RESP_W-1:0] rresp,
      input logic                  rlast,
      input logic [AOU_DATA_W-1:0] rdata);
    mk_readdata256 = {MT_READDATA, rp, DLEN_256, flex, rid, rresp, rlast,
                      3'b0, rdata, 24'b0};
  endfunction

  // WriteResp (Table 13): MSGTYPE,RP,RsvdZero(2),FLEX,BID,BRESP,RsvdZero(4)
  //                       => 40b (1 granule) left-justified in 320b
  function automatic msg_t mk_writeresp(
      input logic [RP_W-1:0]       rp,
      input logic [FLEX_W-1:0]     flex,
      input logic [AOU_ID_W-1:0]   bid,
      input logic [AOU_RESP_W-1:0] bresp);
    logic [WRITERESP_BITS-1:0] v;
    begin
      v = {MT_WRITERESP, rp, 2'b0, flex, bid, bresp, 4'b0};
      mk_writeresp = {v, {(MSG_MAX_BITS-WRITERESP_BITS){1'b0}}};
    end
  endfunction

  // =========================================================================
  // Field extractors.  Input `m` is a left-justified MSG_MAX_BITS slice (the
  // unpacker builds it by taking N granules from the payload and zero-padding
  // the low bits).  MSGTYPE is always m[MSG_MAX_BITS-1 -: 4].
  // =========================================================================
  function automatic logic [MSGTYPE_W-1:0] get_msgtype(input msg_t m);
    get_msgtype = m[MSG_MAX_BITS-1 -: MSGTYPE_W];
  endfunction

  // WriteReq field getters
  function automatic logic [AOU_ADDR_W-1:0] wr_addr(input msg_t m);
    // AWADDR is the last (LSB) field of the 120b message
    wr_addr = m[(MSG_MAX_BITS-WRITEREQ_BITS) +: AOU_ADDR_W];
  endfunction
  function automatic logic [AOU_ID_W-1:0] wr_id(input msg_t m);
    // AWID sits after MSGTYPE(4),RP(2),RsvdZero(1),AWLOCK(1),FLEX(16) = 24 bits
    wr_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [FLEX_W-1:0] wr_flex(input msg_t m);
    wr_flex = m[MSG_MAX_BITS-1-8 -: FLEX_W];  // after 4+2+1+1 = 8 bits
  endfunction

  // ReadReq field getters (identical layout to WriteReq)
  function automatic logic [AOU_ADDR_W-1:0] rr_addr(input msg_t m);
    rr_addr = m[(MSG_MAX_BITS-READREQ_BITS) +: AOU_ADDR_W];
  endfunction
  function automatic logic [AOU_ID_W-1:0] rr_id(input msg_t m);
    rr_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [FLEX_W-1:0] rr_flex(input msg_t m);
    rr_flex = m[MSG_MAX_BITS-1-8 -: FLEX_W];
  endfunction

  // WriteData256 getters: after MSGTYPE(4),RP(2),DLENGTH(2),FLEX(16) = 24 bits
  function automatic logic [AOU_DATA_W-1:0] wd_data(input msg_t m);
    wd_data = m[MSG_MAX_BITS-1-24 -: AOU_DATA_W];
  endfunction
  function automatic logic [AOU_STRB_W-1:0] wd_strb(input msg_t m);
    wd_strb = m[MSG_MAX_BITS-1-24-AOU_DATA_W -: AOU_STRB_W];
  endfunction

  // ReadData256 getters: MSGTYPE(4),RP(2),DLENGTH(2),FLEX(16),RID(10),
  //   RRESP(2),RLAST(1),RsvdZero(3) then RDATA(256)
  function automatic logic [AOU_ID_W-1:0] rd_id(input msg_t m);
    rd_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [AOU_RESP_W-1:0] rd_resp(input msg_t m);
    rd_resp = m[MSG_MAX_BITS-1-34 -: AOU_RESP_W];  // after 24+10
  endfunction
  function automatic logic rd_last(input msg_t m);
    rd_last = m[MSG_MAX_BITS-1-36];                // after 24+10+2
  endfunction
  function automatic logic [AOU_DATA_W-1:0] rd_data(input msg_t m);
    rd_data = m[MSG_MAX_BITS-1-40 -: AOU_DATA_W];  // after 24+10+2+1+3 = 40
  endfunction

  // WriteResp getters: after MSGTYPE(4),RP(2),RsvdZero(2),FLEX(16) = 24 bits
  function automatic logic [AOU_ID_W-1:0] wrsp_id(input msg_t m);
    wrsp_id = m[MSG_MAX_BITS-1-24 -: AOU_ID_W];
  endfunction
  function automatic logic [AOU_RESP_W-1:0] wrsp_resp(input msg_t m);
    wrsp_resp = m[MSG_MAX_BITS-1-34 -: AOU_RESP_W];
  endfunction

  // =========================================================================
  // Flit assembly / disassembly (spec §4.2-4.3).
  //   Header layout (MSB-first): FDId(2) | MsgStart(48) | MsgCredit(16) |
  //   Rsvd(14), followed by the 1920b payload.  Credit is always 0 in this
  //   build (no flow control yet).
  // =========================================================================
  function automatic flit_t flit_assemble(input logic [FDID_W-1:0] fdid,
                                           input msgstart_t         msgstart,
                                           input payload_t          payload);
    flit_assemble = {fdid, msgstart, {CREDIT_W{1'b0}}, {HDR_RSVD_W{1'b0}},
                     payload};
  endfunction

  function automatic msgstart_t flit_msgstart(input flit_t f);
    flit_msgstart = f[PLP_BITS-1-FDID_W -: NUM_GRAN];
  endfunction

  function automatic payload_t flit_payload(input flit_t f);
    flit_payload = f[PLP_PAYLOAD_BITS-1:0];
  endfunction

  // Place a (left-justified) message of `gran` granules into a payload at
  // granule `g`.  Returns the payload bits to be OR-ed / assigned.
  function automatic payload_t payload_put(input payload_t base,
                                           input int       g,
                                           input int       gran,
                                           input msg_t     m);
    payload_t p;
    begin
      p = base;
      // granule g occupies payload[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: 40];
      // a `gran`-granule message spans gran*GRAN_BITS bits from that top.
      for (int b = 0; b < gran*GRAN_BITS; b++)
        p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS - b] = m[MSG_MAX_BITS-1 - b];
      payload_put = p;
    end
  endfunction

  // Extract the message that starts at granule `g` (length `gran`) from a
  // payload, returned left-justified in an MSG_MAX_BITS container.
  function automatic msg_t payload_get(input payload_t p,
                                       input int       g,
                                       input int       gran);
    msg_t m;
    begin
      m = '0;
      for (int b = 0; b < gran*GRAN_BITS; b++)
        m[MSG_MAX_BITS-1 - b] = p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS - b];
      payload_get = m;
    end
  endfunction

  // MSGTYPE of the message starting at granule g (top 4 bits of that granule).
  function automatic logic [MSGTYPE_W-1:0] payload_msgtype(input payload_t p,
                                                           input int g);
    payload_msgtype = p[PLP_PAYLOAD_BITS-1 - g*GRAN_BITS -: MSGTYPE_W];
  endfunction

endpackage : aou_pkg
// verilator lint_on UNUSEDSIGNAL
// verilator lint_on UNUSEDPARAM

`endif

// ==================== rtl/ucie_stream_link.sv ====================
// -----------------------------------------------------------------------------
// ucie_stream_link : one-directional flit transport across the FDI boundary.
//
// Models a UCIe streaming (FDI) link as a registered valid/ready flit channel.
// This is deliberately ABOVE the UCIe PHY / Die-to-Die Adapter: everything below
// FDI (electrical, retry, CRC, sideband) is UCIe's own concern and
// IMPLEMENTATION DEFINED per the AoU spec, so it is not modeled here.  A 1-deep
// skid buffer gives one cycle of latency, decouples the two bridges' handshakes,
// and sustains one flit per cycle.
// -----------------------------------------------------------------------------
`ifndef UCIE_STREAM_LINK_SV
`define UCIE_STREAM_LINK_SV

module ucie_stream_link #(
    parameter int W = 2000               // flit width (PLP = 250B = 2000b)
) (
    input  logic         clk,
    input  logic         rstn,
    // upstream (transmit side)
    input  logic [W-1:0] in_data,
    input  logic         in_valid,
    output logic         in_ready,
    // downstream (receive side)
    output logic [W-1:0] out_data,
    output logic         out_valid,
    input  logic         out_ready
);

  logic         full;
  logic [W-1:0] data_q;

  assign out_valid = full;
  assign out_data  = data_q;
  // can accept when empty, or when the held flit is being taken this cycle
  assign in_ready  = !full || out_ready;

  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      full   <= 1'b0;
      data_q <= '0;
    end else begin
      if (in_valid && in_ready) begin
        data_q <= in_data;
        full   <= 1'b1;
      end else if (out_valid && out_ready) begin
        full   <= 1'b0;
      end
    end
  end

endmodule
`endif

// ==================== rtl/axi_lite_mem.sv ====================
// -----------------------------------------------------------------------------
// axi_lite_mem : AXI4-Lite word-wide SRAM memory (the far-side target).
//
// Replaces the APB memory of ../uvm_review with a native AXI4-Lite slave, since
// AXI is the OCA non-coherent bus protocol carried over UCIe (OCA §5.2); APB is
// a low-speed peripheral bus not intended for a die-to-die link.  Reuses the
// reference's memory idioms: zero-initialised array (reads of un-written
// locations return 0), plain `always @(posedge)` write (portable to VCS, which
// rejects a second driver on an `always_ff` variable), and constant OKAY
// responses (this slave never errors).
//
//  * Data width  : DATA_W bits (default 32, word)
//  * Address     : byte address, ADDR_W bits; word index = ADDR[ADDR_W-1:2]
//  * Wait states : none (single-cycle accept + response)
//  * Responses   : BRESP/RRESP tied to OKAY
// -----------------------------------------------------------------------------
`ifndef AXI_LITE_MEM_SV
`define AXI_LITE_MEM_SV

module axi_lite_mem #(
    parameter int ADDR_W = 16,          // byte address width -> 64 KiB
    parameter int DATA_W = 32,
    parameter int STRB_W = DATA_W/8
) (
    input  logic              ACLK,
    input  logic              ARESETn,
    // write address channel
    input  logic [ADDR_W-1:0] AWADDR,
    input  logic [2:0]        AWPROT,
    input  logic              AWVALID,
    output logic              AWREADY,
    // write data channel
    input  logic [DATA_W-1:0] WDATA,
    input  logic [STRB_W-1:0] WSTRB,
    input  logic              WVALID,
    output logic              WREADY,
    // write response channel
    output logic [1:0]        BRESP,
    output logic              BVALID,
    input  logic              BREADY,
    // read address channel
    input  logic [ADDR_W-1:0] ARADDR,
    input  logic [2:0]        ARPROT,
    input  logic              ARVALID,
    output logic              ARREADY,
    // read data channel
    output logic [DATA_W-1:0] RDATA,
    output logic [1:0]        RRESP,
    output logic              RVALID,
    input  logic              RREADY
);

  localparam int WORDS = 1 << (ADDR_W-2);
  localparam logic [1:0] RESP_OKAY = 2'b00;

  // AXI requires AxPROT and full-width AxADDR on the bus, but a word memory
  // ignores protection bits and the two low (sub-word) address bits.  Sink
  // them so the (correct) "intentionally unused" lint stays visible elsewhere.
  // verilator lint_off UNUSEDSIGNAL
  wire _unused_ok = &{1'b0, AWPROT, ARPROT, AWADDR[1:0], ARADDR[1:0]};
  // verilator lint_on UNUSEDSIGNAL

  logic [DATA_W-1:0] mem [0:WORDS-1];

  // Power up all-zero so reads of un-written locations return 0 (not X).
  integer i;
  initial begin
    for (i = 0; i < WORDS; i = i + 1) mem[i] = '0;
  end

  // verilator coverage_off
  // Constant tie-offs: this slave never errors -> no logic to cover.
  assign BRESP = RESP_OKAY;
  assign RRESP = RESP_OKAY;
  // verilator coverage_on

  // --- Write channel --------------------------------------------------------
  // Capture AW and W independently, commit the write once both are held.
  logic                aw_taken, w_taken;
  logic [ADDR_W-3:0]   awaddr_q;   // captured word index (drops sub-word bits)
  logic [DATA_W-1:0]   wdata_q;
  logic [STRB_W-1:0]   wstrb_q;

  assign AWREADY = !aw_taken;
  assign WREADY  = !w_taken;

  wire do_write = aw_taken && w_taken && !BVALID;

  // plain always (not always_ff) — see header note on the memory array driver.
  always @(posedge ACLK or negedge ARESETn) begin
    if (!ARESETn) begin
      aw_taken <= 1'b0;
      w_taken  <= 1'b0;
      awaddr_q <= '0;
      wdata_q  <= '0;
      wstrb_q  <= '0;
      BVALID   <= 1'b0;
    end else begin
      if (AWVALID && AWREADY) begin
        aw_taken <= 1'b1;
        awaddr_q <= AWADDR[ADDR_W-1:2];
      end
      if (WVALID && WREADY) begin
        w_taken <= 1'b1;
        wdata_q <= WDATA;
        wstrb_q <= WSTRB;
      end
      if (do_write) begin
        // byte-strobed write into the addressed word
        for (int b = 0; b < STRB_W; b++)
          if (wstrb_q[b])
            mem[awaddr_q][b*8 +: 8] <= wdata_q[b*8 +: 8];
        aw_taken <= 1'b0;
        w_taken  <= 1'b0;
        BVALID   <= 1'b1;
      end else if (BVALID && BREADY) begin
        BVALID <= 1'b0;
      end
    end
  end

  // --- Read channel ---------------------------------------------------------
  logic ar_taken;
  assign ARREADY = !ar_taken && !RVALID;

  always @(posedge ACLK or negedge ARESETn) begin
    if (!ARESETn) begin
      ar_taken <= 1'b0;
      RVALID   <= 1'b0;
      RDATA    <= '0;
    end else begin
      if (ARVALID && ARREADY) begin
        RDATA    <= mem[ARADDR[ADDR_W-1:2]];
        RVALID   <= 1'b1;
        ar_taken <= 1'b0;   // single-cycle: data ready next cycle
      end
      if (RVALID && RREADY) begin
        RVALID <= 1'b0;
      end
    end
  end

endmodule
`endif

// ==================== rtl/aou_axi_initiator_bridge.sv ====================
// -----------------------------------------------------------------------------
// aou_axi_initiator_bridge : chiplet-A bridge (AXI-Lite subordinate -> AoU).
//
// Accepts AXI4-Lite transactions from the TB master and turns them into AoU
// Basic-Profile messages packed into a flit sent over the A->B link:
//   * write  -> {WriteReq (g0), WriteData256 (g3)}   (MsgStart = bit0 | bit3)
//   * read   -> {ReadReq  (g0)}                       (MsgStart = bit0)
// The return flit from B->A carries a WriteResp or ReadData256 message, which is
// unpacked to complete the AXI B / R response.
//
// Scope: one transaction in flight at a time (single-outstanding).  A monotonic
// tag is carried in the AoU {AW,AR}ID field and echoed back in {B,R}ID for
// faithfulness; response routing is trivial with one outstanding transaction.
// Multiple-outstanding + credit flow control is a documented follow-on.
// -----------------------------------------------------------------------------
`ifndef AOU_AXI_INITIATOR_BRIDGE_SV
`define AOU_AXI_INITIATOR_BRIDGE_SV

module aou_axi_initiator_bridge
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8
) (
    input  logic                    clk,
    input  logic                    rstn,
    // ---- AXI4-Lite subordinate (TB master drives these) ----
    input  logic [AXI_ADDR_W-1:0]   s_awaddr,
    input  logic [2:0]              s_awprot,
    input  logic                    s_awvalid,
    output logic                    s_awready,
    input  logic [AXI_DATA_W-1:0]   s_wdata,
    input  logic [AXI_STRB_W-1:0]   s_wstrb,
    input  logic                    s_wvalid,
    output logic                    s_wready,
    output logic [1:0]              s_bresp,
    output logic                    s_bvalid,
    input  logic                    s_bready,
    input  logic [AXI_ADDR_W-1:0]   s_araddr,
    input  logic [2:0]              s_arprot,
    input  logic                    s_arvalid,
    output logic                    s_arready,
    output logic [AXI_DATA_W-1:0]   s_rdata,
    output logic [1:0]              s_rresp,
    output logic                    s_rvalid,
    input  logic                    s_rready,
    // ---- flit TX (to A->B link) ----
    output logic [PLP_BITS-1:0]     tx_data,
    output logic                    tx_valid,
    input  logic                    tx_ready,
    // ---- flit RX (from B->A link) ----
    input  logic [PLP_BITS-1:0]     rx_data,
    input  logic                    rx_valid,
    output logic                    rx_ready
);

  typedef enum logic [2:0] {
    S_IDLE, S_WSEND, S_RSEND, S_WAIT, S_B, S_R
  } state_e;
  state_e state;

  logic                  aw_seen, w_seen, is_write;
  logic [AXI_ADDR_W-1:0] awaddr_q, araddr_q;
  logic [2:0]            awprot_q, arprot_q;
  logic [AXI_DATA_W-1:0] wdata_q;
  logic [AXI_STRB_W-1:0] wstrb_q;
  logic [AOU_ID_W-1:0]   id_q, id_ctr;
  logic [1:0]            bresp_q, rresp_q;
  logic [AXI_DATA_W-1:0] rdata_q;

  localparam logic [2:0] AXSIZE_4B = 3'b010;   // 32-bit beat

  // --- build the outgoing flits (combinational from captured regs) ----------
  function automatic flit_t build_write_flit();
    msg_t     m_wreq, m_wdata;
    payload_t pl;
    begin
      m_wreq  = mk_writereq(2'b00, 1'b0, '0, id_q, AXSIZE_4B, awprot_q,
                            '0, '0, '0,
                            {{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, awaddr_q});
      m_wdata = mk_writedata256(2'b00, '0,
                            {{(AOU_DATA_W-AXI_DATA_W){1'b0}}, wdata_q},
                            {{(AOU_STRB_W-AXI_STRB_W){1'b0}}, wstrb_q});
      pl = payload_put('0,            0,             WRITEREQ_GRAN,  m_wreq);
      pl = payload_put(pl, WRITEREQ_GRAN, WRITEDATA_GRAN, m_wdata);
      build_write_flit = flit_assemble('0,
                           (msgstart_t'(1) << 0) | (msgstart_t'(1) << WRITEREQ_GRAN),
                           pl);
    end
  endfunction

  function automatic flit_t build_read_flit();
    msg_t     m_rreq;
    payload_t pl;
    begin
      m_rreq = mk_readreq(2'b00, 1'b0, '0, id_q, AXSIZE_4B, arprot_q,
                          '0, '0, '0,
                          {{(AOU_ADDR_W-AXI_ADDR_W){1'b0}}, araddr_q});
      pl = payload_put('0, 0, READREQ_GRAN, m_rreq);
      build_read_flit = flit_assemble('0, (msgstart_t'(1) << 0), pl);
    end
  endfunction

  // --- combinational outputs ------------------------------------------------
  assign s_awready = (state == S_IDLE) && !aw_seen;
  assign s_wready  = (state == S_IDLE) && !w_seen;
  assign s_arready = (state == S_IDLE) && !aw_seen && !w_seen;
  assign s_bvalid  = (state == S_B);
  assign s_bresp   = bresp_q;
  assign s_rvalid  = (state == S_R);
  assign s_rdata   = rdata_q;
  assign s_rresp   = rresp_q;
  assign tx_valid  = (state == S_WSEND) || (state == S_RSEND);
  assign rx_ready  = (state == S_WAIT);

  // Build the outgoing flit procedurally: Icarus 11 mis-generates a wide
  // function call placed directly in a continuous assign, so drive it from an
  // always_comb into a register-free net instead.
  always_comb begin
    if (state == S_WSEND) tx_data = build_write_flit();
    else                  tx_data = build_read_flit();
  end

  // --- FSM ------------------------------------------------------------------
  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      state    <= S_IDLE;
      aw_seen  <= 1'b0;
      w_seen   <= 1'b0;
      is_write <= 1'b0;
      id_ctr   <= '0;
      id_q     <= '0;
      awaddr_q <= '0; awprot_q <= '0;
      araddr_q <= '0; arprot_q <= '0;
      wdata_q  <= '0; wstrb_q  <= '0;
      bresp_q  <= '0; rresp_q  <= '0; rdata_q <= '0;
    end else begin
      unique case (state)
        S_IDLE: begin : s_idle_blk
          logic aw_now, w_now;
          aw_now = aw_seen;
          w_now  = w_seen;
          if (s_awvalid && s_awready) begin
            aw_seen  <= 1'b1; aw_now = 1'b1;
            awaddr_q <= s_awaddr; awprot_q <= s_awprot;
          end
          if (s_wvalid && s_wready) begin
            w_seen  <= 1'b1; w_now = 1'b1;
            wdata_q <= s_wdata; wstrb_q <= s_wstrb;
          end
          if (aw_now && w_now) begin
            is_write <= 1'b1;
            id_q     <= id_ctr;
            id_ctr   <= id_ctr + 1'b1;
            state    <= S_WSEND;
          end else if (s_arvalid && s_arready) begin
            araddr_q <= s_araddr; arprot_q <= s_arprot;
            is_write <= 1'b0;
            id_q     <= id_ctr;
            id_ctr   <= id_ctr + 1'b1;
            state    <= S_RSEND;
          end
        end
        S_WSEND: if (tx_ready) begin
          aw_seen <= 1'b0; w_seen <= 1'b0; state <= S_WAIT;
        end
        S_RSEND: if (tx_ready) state <= S_WAIT;
        S_WAIT: if (rx_valid) begin : s_wait_blk
          payload_t              rpl;
          msg_t                  m;
          // AoU RDATA is 256b; only the low AXI_DATA_W bits carry this design's
          // 32-bit beat — the rest is intentionally dropped.
          // verilator lint_off UNUSEDSIGNAL
          logic [AOU_DATA_W-1:0] rd_full;
          // verilator lint_on UNUSEDSIGNAL
          rpl = flit_payload(rx_data);
          if (is_write) begin
            m        = payload_get(rpl, 0, WRITERESP_GRAN);
            bresp_q <= wrsp_resp(m);
            state   <= S_B;
          end else begin
            m        = payload_get(rpl, 0, READDATA_GRAN);
            rd_full  = rd_data(m);
            rdata_q <= rd_full[AXI_DATA_W-1:0];
            rresp_q <= rd_resp(m);
            state   <= S_R;
          end
        end
        S_B: if (s_bready) state <= S_IDLE;
        S_R: if (s_rready) state <= S_IDLE;
        // verilator coverage_off
        default: state <= S_IDLE;   // unreachable (all states enumerated)
        // verilator coverage_on
      endcase
    end
  end

endmodule
`endif

// ==================== rtl/aou_axi_target_bridge.sv ====================
// -----------------------------------------------------------------------------
// aou_axi_target_bridge : chiplet-B bridge (AoU -> AXI-Lite manager).
//
// Unpacks a flit arriving on the A->B link by walking its MsgStart[47:0] bitmap,
// decodes the AoU messages, and drives an AXI4-Lite manager into the memory:
//   * {WriteReq, WriteData256} -> AXI write  -> WriteResp   flit back on B->A
//   * {ReadReq}                -> AXI read    -> ReadData256 flit back on B->A
// The AoU {AW,AR}ID tag is echoed into the {B,R}ID of the response.
//
// Single-outstanding, matching the initiator bridge.
// -----------------------------------------------------------------------------
`ifndef AOU_AXI_TARGET_BRIDGE_SV
`define AOU_AXI_TARGET_BRIDGE_SV

module aou_axi_target_bridge
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8
) (
    input  logic                    clk,
    input  logic                    rstn,
    // ---- flit RX (from A->B link) ----
    input  logic [PLP_BITS-1:0]     rx_data,
    input  logic                    rx_valid,
    output logic                    rx_ready,
    // ---- flit TX (to B->A link) ----
    output logic [PLP_BITS-1:0]     tx_data,
    output logic                    tx_valid,
    input  logic                    tx_ready,
    // ---- AXI4-Lite manager (drives the memory) ----
    output logic [AXI_ADDR_W-1:0]   m_awaddr,
    output logic [2:0]              m_awprot,
    output logic                    m_awvalid,
    input  logic                    m_awready,
    output logic [AXI_DATA_W-1:0]   m_wdata,
    output logic [AXI_STRB_W-1:0]   m_wstrb,
    output logic                    m_wvalid,
    input  logic                    m_wready,
    input  logic [1:0]              m_bresp,
    input  logic                    m_bvalid,
    output logic                    m_bready,
    output logic [AXI_ADDR_W-1:0]   m_araddr,
    output logic [2:0]              m_arprot,
    output logic                    m_arvalid,
    input  logic                    m_arready,
    input  logic [AXI_DATA_W-1:0]   m_rdata,
    input  logic [1:0]              m_rresp,
    input  logic                    m_rvalid,
    output logic                    m_rready
);

  typedef enum logic [2:0] {
    S_IDLE, S_WMEM, S_WRESP, S_RMEM, S_RDATA
  } state_e;
  state_e state;

  logic [AXI_ADDR_W-1:0] awaddr_q, araddr_q;
  logic [AXI_DATA_W-1:0] wdata_q, rdata_q;
  logic [AXI_STRB_W-1:0] wstrb_q;
  logic [AOU_ID_W-1:0]   id_q;
  logic [1:0]            bresp_q, rresp_q;
  logic                  aw_done, w_done, ar_done;

  // --- build the response flits (combinational) -----------------------------
  function automatic flit_t build_wresp_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_writeresp(2'b00, '0, id_q, bresp_q);
      pl = payload_put('0, 0, WRITERESP_GRAN, m);
      build_wresp_flit = flit_assemble('0, msgstart_t'(1), pl);
    end
  endfunction

  function automatic flit_t build_rdata_flit();
    msg_t m; payload_t pl;
    begin
      m  = mk_readdata256(2'b00, '0, id_q, rresp_q, 1'b1,
                          {{(AOU_DATA_W-AXI_DATA_W){1'b0}}, rdata_q});
      pl = payload_put('0, 0, READDATA_GRAN, m);
      build_rdata_flit = flit_assemble('0, msgstart_t'(1), pl);
    end
  endfunction

  // --- combinational outputs ------------------------------------------------
  assign rx_ready  = (state == S_IDLE);
  assign m_awaddr  = awaddr_q;
  assign m_awprot  = 3'b000;
  assign m_awvalid = (state == S_WMEM) && !aw_done;
  assign m_wdata   = wdata_q;
  assign m_wstrb   = wstrb_q;
  assign m_wvalid  = (state == S_WMEM) && !w_done;
  assign m_bready  = (state == S_WMEM);
  assign m_araddr  = araddr_q;
  assign m_arprot  = 3'b000;
  assign m_arvalid = (state == S_RMEM) && !ar_done;
  assign m_rready  = (state == S_RMEM);
  assign tx_valid  = (state == S_WRESP) || (state == S_RDATA);

  // Procedural build (see the initiator bridge note on Icarus 11 wide-ufunc).
  always_comb begin
    if (state == S_WRESP) tx_data = build_wresp_flit();
    else                  tx_data = build_rdata_flit();
  end

  // --- FSM ------------------------------------------------------------------
  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      state    <= S_IDLE;
      awaddr_q <= '0; araddr_q <= '0;
      wdata_q  <= '0; rdata_q  <= '0; wstrb_q <= '0;
      id_q     <= '0; bresp_q  <= '0; rresp_q <= '0;
      aw_done  <= 1'b0; w_done <= 1'b0; ar_done <= 1'b0;
    end else begin
      unique case (state)
        S_IDLE: if (rx_valid) begin : s_idle_blk
          payload_t              pl;
          msgstart_t             ms;
          msg_t                  m0, m1;
          int                    s0, s1, cnt;
          // AoU addr/data/strb are 64/256/32b; only the low AXI-Lite widths are
          // used (this design's 32-bit beat) — upper bits intentionally dropped.
          // verilator lint_off UNUSEDSIGNAL
          logic [AOU_ADDR_W-1:0] addr_full;
          logic [AOU_DATA_W-1:0] wd_full;
          logic [AOU_STRB_W-1:0] ws_full;
          // verilator lint_on UNUSEDSIGNAL
          pl  = flit_payload(rx_data);
          ms  = flit_msgstart(rx_data);
          // walk MsgStart: locate the (up to two) message-start granules
          s0 = 0; s1 = 0; cnt = 0;
          for (int g = 0; g < NUM_GRAN; g++) begin
            if (ms[g]) begin
              if (cnt == 0) s0 = g;
              else if (cnt == 1) s1 = g;
              cnt = cnt + 1;
            end
          end
          if (payload_msgtype(pl, s0) == MT_WRITEREQ) begin
            m0        = payload_get(pl, s0, WRITEREQ_GRAN);
            m1        = payload_get(pl, s1, WRITEDATA_GRAN);
            addr_full = wr_addr(m0);
            wd_full   = wd_data(m1);
            ws_full   = wd_strb(m1);
            awaddr_q <= addr_full[AXI_ADDR_W-1:0];
            id_q     <= wr_id(m0);
            wdata_q  <= wd_full[AXI_DATA_W-1:0];
            wstrb_q  <= ws_full[AXI_STRB_W-1:0];
            aw_done  <= 1'b0; w_done <= 1'b0;
            state    <= S_WMEM;
          end else begin // MT_READREQ
            m0        = payload_get(pl, s0, READREQ_GRAN);
            addr_full = rr_addr(m0);
            araddr_q <= addr_full[AXI_ADDR_W-1:0];
            id_q     <= rr_id(m0);
            ar_done  <= 1'b0;
            state    <= S_RMEM;
          end
        end
        S_WMEM: begin
          if (m_awvalid && m_awready) aw_done <= 1'b1;
          if (m_wvalid  && m_wready ) w_done  <= 1'b1;
          if (m_bvalid  && m_bready ) begin
            bresp_q <= m_bresp;
            aw_done <= 1'b0; w_done <= 1'b0;
            state   <= S_WRESP;
          end
        end
        S_WRESP: if (tx_ready) state <= S_IDLE;
        S_RMEM: begin
          if (m_arvalid && m_arready) ar_done <= 1'b1;
          if (m_rvalid  && m_rready ) begin
            rdata_q <= m_rdata;
            rresp_q <= m_rresp;
            ar_done <= 1'b0;
            state   <= S_RDATA;
          end
        end
        S_RDATA: if (tx_ready) state <= S_IDLE;
        // verilator coverage_off
        default: state <= S_IDLE;   // unreachable (all states enumerated)
        // verilator coverage_on
      endcase
    end
  end

endmodule
`endif

// ==================== rtl/axi_ucie_mem_top.sv ====================
// -----------------------------------------------------------------------------
// axi_ucie_mem_top : DUT top — AXI-Lite over UCIe (AoU) to an AXI-Lite memory.
//
//   TB AXI-Lite master
//        -> aou_axi_initiator_bridge  (chiplet A: AXI-Lite SUB -> AoU flits)
//        == ucie_stream_link A->B ==>
//        -> aou_axi_target_bridge     (chiplet B: AoU flits -> AXI-Lite MGR)
//        -> axi_lite_mem              (the memory)
//        <= ucie_stream_link B->A <=  (WriteResp / ReadData flits)
//
// Flat AXI-Lite ports on the boundary (no SystemVerilog interface) so the same
// DUT is drivable from cocotb, a portable SV TB, a Verilator SystemC harness,
// and UVM without wrapper shims.
// -----------------------------------------------------------------------------
`ifndef AXI_UCIE_MEM_TOP_SV
`define AXI_UCIE_MEM_TOP_SV

module axi_ucie_mem_top
  import aou_pkg::*;
#(
    parameter int AXI_ADDR_W = 32,
    parameter int AXI_DATA_W = 32,
    parameter int AXI_STRB_W = AXI_DATA_W/8,
    parameter int MEM_ADDR_W = 16          // memory byte-address width (64 KiB)
) (
    input  logic                  ACLK,
    input  logic                  ARESETn,
    // AXI4-Lite subordinate (TB master side)
    input  logic [AXI_ADDR_W-1:0] AWADDR,
    input  logic [2:0]            AWPROT,
    input  logic                  AWVALID,
    output logic                  AWREADY,
    input  logic [AXI_DATA_W-1:0] WDATA,
    input  logic [AXI_STRB_W-1:0] WSTRB,
    input  logic                  WVALID,
    output logic                  WREADY,
    output logic [1:0]            BRESP,
    output logic                  BVALID,
    input  logic                  BREADY,
    input  logic [AXI_ADDR_W-1:0] ARADDR,
    input  logic [2:0]            ARPROT,
    input  logic                  ARVALID,
    output logic                  ARREADY,
    output logic [AXI_DATA_W-1:0] RDATA,
    output logic [1:0]            RRESP,
    output logic                  RVALID,
    input  logic                  RREADY
);

  // --- flit links (both directions) -----------------------------------------
  logic [PLP_BITS-1:0] a2b_data, b2a_data;
  logic                a2b_valid, a2b_ready, b2a_valid, b2a_ready;

  // initiator side of each link (as seen by the initiator bridge)
  logic [PLP_BITS-1:0] init_tx_data, init_rx_data;
  logic                init_tx_valid, init_tx_ready, init_rx_valid, init_rx_ready;
  // target side of each link
  logic [PLP_BITS-1:0] tgt_tx_data, tgt_rx_data;
  logic                tgt_tx_valid, tgt_tx_ready, tgt_rx_valid, tgt_rx_ready;

  // --- chiplet-B AXI-Lite manager <-> memory --------------------------------
  logic [AXI_ADDR_W-1:0] m_awaddr, m_araddr;
  logic [2:0]            m_awprot, m_arprot;
  logic                  m_awvalid, m_awready, m_wvalid, m_wready;
  logic [AXI_DATA_W-1:0] m_wdata, m_rdata;
  logic [AXI_STRB_W-1:0] m_wstrb;
  logic [1:0]            m_bresp, m_rresp;
  logic                  m_bvalid, m_bready, m_arvalid, m_arready, m_rvalid, m_rready;

  // === Chiplet A: initiator bridge =========================================
  aou_axi_initiator_bridge #(
    .AXI_ADDR_W(AXI_ADDR_W), .AXI_DATA_W(AXI_DATA_W), .AXI_STRB_W(AXI_STRB_W)
  ) u_init (
    .clk(ACLK), .rstn(ARESETn),
    .s_awaddr(AWADDR), .s_awprot(AWPROT), .s_awvalid(AWVALID), .s_awready(AWREADY),
    .s_wdata(WDATA),   .s_wstrb(WSTRB),   .s_wvalid(WVALID),   .s_wready(WREADY),
    .s_bresp(BRESP),   .s_bvalid(BVALID), .s_bready(BREADY),
    .s_araddr(ARADDR), .s_arprot(ARPROT), .s_arvalid(ARVALID), .s_arready(ARREADY),
    .s_rdata(RDATA),   .s_rresp(RRESP),   .s_rvalid(RVALID),   .s_rready(RREADY),
    .tx_data(init_tx_data), .tx_valid(init_tx_valid), .tx_ready(init_tx_ready),
    .rx_data(init_rx_data), .rx_valid(init_rx_valid), .rx_ready(init_rx_ready)
  );

  // === A->B link ============================================================
  ucie_stream_link #(.W(PLP_BITS)) u_link_a2b (
    .clk(ACLK), .rstn(ARESETn),
    .in_data(init_tx_data), .in_valid(init_tx_valid), .in_ready(init_tx_ready),
    .out_data(a2b_data),    .out_valid(a2b_valid),    .out_ready(a2b_ready)
  );
  assign tgt_rx_data  = a2b_data;
  assign tgt_rx_valid = a2b_valid;
  assign a2b_ready    = tgt_rx_ready;

  // === B->A link ============================================================
  ucie_stream_link #(.W(PLP_BITS)) u_link_b2a (
    .clk(ACLK), .rstn(ARESETn),
    .in_data(tgt_tx_data), .in_valid(tgt_tx_valid), .in_ready(tgt_tx_ready),
    .out_data(b2a_data),   .out_valid(b2a_valid),   .out_ready(b2a_ready)
  );
  assign init_rx_data  = b2a_data;
  assign init_rx_valid = b2a_valid;
  assign b2a_ready     = init_rx_ready;

  // === Chiplet B: target bridge ============================================
  aou_axi_target_bridge #(
    .AXI_ADDR_W(AXI_ADDR_W), .AXI_DATA_W(AXI_DATA_W), .AXI_STRB_W(AXI_STRB_W)
  ) u_tgt (
    .clk(ACLK), .rstn(ARESETn),
    .rx_data(tgt_rx_data), .rx_valid(tgt_rx_valid), .rx_ready(tgt_rx_ready),
    .tx_data(tgt_tx_data), .tx_valid(tgt_tx_valid), .tx_ready(tgt_tx_ready),
    .m_awaddr(m_awaddr), .m_awprot(m_awprot), .m_awvalid(m_awvalid), .m_awready(m_awready),
    .m_wdata(m_wdata),   .m_wstrb(m_wstrb),   .m_wvalid(m_wvalid),   .m_wready(m_wready),
    .m_bresp(m_bresp),   .m_bvalid(m_bvalid), .m_bready(m_bready),
    .m_araddr(m_araddr), .m_arprot(m_arprot), .m_arvalid(m_arvalid), .m_arready(m_arready),
    .m_rdata(m_rdata),   .m_rresp(m_rresp),   .m_rvalid(m_rvalid),   .m_rready(m_rready)
  );

  // === Chiplet B: AXI-Lite memory ==========================================
  axi_lite_mem #(
    .ADDR_W(MEM_ADDR_W), .DATA_W(AXI_DATA_W), .STRB_W(AXI_STRB_W)
  ) u_mem (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .AWADDR(m_awaddr[MEM_ADDR_W-1:0]), .AWPROT(m_awprot), .AWVALID(m_awvalid), .AWREADY(m_awready),
    .WDATA(m_wdata), .WSTRB(m_wstrb), .WVALID(m_wvalid), .WREADY(m_wready),
    .BRESP(m_bresp), .BVALID(m_bvalid), .BREADY(m_bready),
    .ARADDR(m_araddr[MEM_ADDR_W-1:0]), .ARPROT(m_arprot), .ARVALID(m_arvalid), .ARREADY(m_arready),
    .RDATA(m_rdata), .RRESP(m_rresp), .RVALID(m_rvalid), .RREADY(m_rready)
  );

  // upper address bits beyond the memory are not decoded (single memory target)
  // verilator lint_off UNUSEDSIGNAL
  wire _unused_ok = &{1'b0, m_awaddr[AXI_ADDR_W-1:MEM_ADDR_W],
                            m_araddr[AXI_ADDR_W-1:MEM_ADDR_W]};
  // verilator lint_on UNUSEDSIGNAL

endmodule
`endif
